<?xml version="1.0" encoding="utf-16"?>
<generator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:type="Assignment" version="2">
  <supportsMaxLength>false</supportsMaxLength>
  <isLibrary>true</isLibrary>
  <items>
    <item name="Career" weight="1">[Administration]</item>
    <item name="Career" weight="1">[Construction]</item>
    <item name="Career" weight="1">[Education]</item>
    <item name="Career" weight="1">[Engineering]</item>
    <item name="Career" weight="1">[Entertainment]</item>
    <item name="Career" weight="1">[Farming]</item>
    <item name="Career" weight="1">[Finance]</item>
    <item name="Career" weight="1">[Food]</item>
    <item name="Career" weight="1">[Government]</item>
    <item name="Career" weight="1">[Health]</item>
    <item name="Career" weight="1">[Legal]</item>
    <item name="Career" weight="1">[Management]</item>
    <item name="Career" weight="1">[Manufacturing]</item>
    <item name="Career" weight="1">[Media]</item>
    <item name="Career" weight="1">[Mining]</item>
    <item name="Career" weight="1">[Science]</item>
    <item name="Career" weight="1">[RealEstate]</item>
    <item name="Career" weight="1">[Volunteer]</item>
    <item name="Career" weight="1">[Retail]</item>
    <item name="Career" weight="1">[Service]</item>
    <item name="Career" weight="1">[Transportation]</item>
    <item name="Administration" weight="1">Account Collector</item>
    <item name="Administration" weight="1">Administrative Assistant</item>
    <item name="Administration" weight="1">Bill Collector</item>
    <item name="Administration" weight="1">Chief Financial Officer</item>
    <item name="Administration" weight="1">Computer Operator</item>
    <item name="Administration" weight="1">Crossing Guard</item>
    <item name="Administration" weight="1">Customer Service Representative</item>
    <item name="Administration" weight="1">Cutting Machine Operator</item>
    <item name="Administration" weight="1">Data Entry Keyer</item>
    <item name="Administration" weight="1">Dispatcher</item>
    <item name="Administration" weight="1">Environmental Science Technician</item>
    <item name="Administration" weight="1">Executive Secretary</item>
    <item name="Administration" weight="1">File Clerk</item>
    <item name="Administration" weight="1">Hand [=Pick('Packer','Packager')]</item>
    <item name="Administration" weight="1">Hazardous Materials Removal Worker</item>
    <item name="Administration" weight="1">Housekeeping Supervisor</item>
    <item name="Administration" weight="1">Janitorial Supervisor</item>
    <item name="Administration" weight="1">Landscape Architect</item>
    <item name="Administration" weight="1">Landscape Contractor</item>
    <item name="Administration" weight="1">Locksmith</item>
    <item name="Administration" weight="1">Mail Clerk</item>
    <item name="Administration" weight="1">Mail Machine Operator</item>
    <item name="Administration" weight="1">Medical Transcriptionist</item>
    <item name="Administration" weight="1">Office Clerk</item>
    <item name="Administration" weight="1">Office Machine Mechanic</item>
    <item name="Administration" weight="1">Offset Press Operators</item>
    <item name="Administration" weight="1">Packaging Machine Operator</item>
    <item name="Administration" weight="1">Pest Control Worker</item>
    <item name="Administration" weight="1">Pesticide Handler</item>
    <item name="Administration" weight="1">Pressing Machine Operator</item>
    <item name="Administration" weight="1">Private [=Pick('Detectives','Investigators')]</item>
    <item name="Administration" weight="1">Safe Repairer</item>
    <item name="Administration" weight="1">Security Guard</item>
    <item name="Administration" weight="1">Switchboard Operator</item>
    <item name="Administration" weight="1">Tax Collector</item>
    <item name="Administration" weight="1">Team Assembler</item>
    <item name="Administration" weight="1">Telemarketer</item>
    <item name="Administration" weight="1">Tour Guide</item>
    <item name="Administration" weight="1">Travel Agent</item>
    <item name="Administration" weight="1">Travel Clerks</item>
    <item name="Administration" weight="1">Travel Counselor</item>
    <item name="Administration" weight="1">Tree Trimmer</item>
    <item name="Administration" weight="1">Utility Meter Reader</item>
    <item name="Administration" weight="1">[=Pick('Demonstrators','Product Promoters')]</item>
    <item name="Administration" weight="1">[=Pick('Forklift','Industrial Truck')] Operators</item>
    <item name="Administration" weight="1">[=Pick('Freight','Stock')] Handler</item>
    <item name="Administration" weight="1">[=Pick('Light Duty','Long Distance')] Truck Driver</item>
    <item name="Administration" weight="1">[=Pick('Refuse','Recyclable')] Material Collector</item>
    <item name="Administration" weight="1">[=Pick('Security','Fire Alarm')] System Installer</item>
    <item name="Administration" weight="1">[=Pick('Weigher','Measurer')]</item>
    <item name="Entertainment" weight="1">Animation Cartoonist</item>
    <item name="Entertainment" weight="1">Art Appraiser</item>
    <item name="Entertainment" weight="1">Art Director</item>
    <item name="Entertainment" weight="1">Art Restorer</item>
    <item name="Entertainment" weight="1">Book Editor</item>
    <item name="Entertainment" weight="1">Cartoonist</item>
    <item name="Entertainment" weight="1">Commercial Designer</item>
    <item name="Entertainment" weight="1">Fabric and Apparel Patternmaker</item>
    <item name="Entertainment" weight="1">Fashion Coordinator</item>
    <item name="Entertainment" weight="1">Film Editor</item>
    <item name="Entertainment" weight="1">Film Laboratory Technician</item>
    <item name="Entertainment" weight="1">Floral Designer</item>
    <item name="Entertainment" weight="1">Furniture Designer</item>
    <item name="Entertainment" weight="1">Furniture Finishers</item>
    <item name="Entertainment" weight="1">Glass Blower</item>
    <item name="Entertainment" weight="1">Graphic Designer</item>
    <item name="Entertainment" weight="1">Interior Designer</item>
    <item name="Entertainment" weight="1">Medical and Scientific Illustrator</item>
    <item name="Entertainment" weight="1">Model Maker</item>
    <item name="Entertainment" weight="1">Museum [=Pick('Technician','Conservator')]</item>
    <item name="Entertainment" weight="1">Ornamental-Metalwork Designer</item>
    <item name="Entertainment" weight="1">Platemaker</item>
    <item name="Entertainment" weight="1">Proofreaders and Copy Marker</item>
    <item name="Entertainment" weight="1">Screen Writer</item>
    <item name="Entertainment" weight="1">Set Designer</item>
    <item name="Entertainment" weight="1">Set Illustrator</item>
    <item name="Entertainment" weight="1">Speech Writer</item>
    <item name="Entertainment" weight="1">Sportswriter (Journalist)</item>
    <item name="Entertainment" weight="1">Technical Illustrator</item>
    <item name="Entertainment" weight="1">Textile Designer</item>
    <item name="Entertainment" weight="1">Web Art Director</item>
    <item name="Entertainment" weight="1">[=Pick('Etcher','Engraver')]</item>
    <item name="Entertainment" weight="1">[=Pick('Poet','Lyricists')]</item>
    <item name="Entertainment" weight="1">[=Pick('Writer','Author')]</item>
    <item name="Construction" weight="1">Building Inspector</item>
    <item name="Construction" weight="1">Building Maintenance Mechanic</item>
    <item name="Construction" weight="1">Cabinet Maker</item>
    <item name="Construction" weight="1">Carpenter's Assistant</item>
    <item name="Construction" weight="1">Carpet Installer</item>
    <item name="Construction" weight="1">Ceiling Tile Installer</item>
    <item name="Construction" weight="1">Cement Mason</item>
    <item name="Construction" weight="1">Construction Driller</item>
    <item name="Construction" weight="1">Construction Laborer</item>
    <item name="Construction" weight="1">Construction Manager</item>
    <item name="Construction" weight="1">Construction Trades Supervisor</item>
    <item name="Construction" weight="1">Construction and Maintenance Painter</item>
    <item name="Construction" weight="1">Cost Estimator</item>
    <item name="Construction" weight="1">Crane Operator</item>
    <item name="Construction" weight="1">Dry Wall Installer</item>
    <item name="Construction" weight="1">Electric Meter Installer</item>
    <item name="Construction" weight="1">Electrical Drafter</item>
    <item name="Construction" weight="1">Electrical and Electronic Inspector</item>
    <item name="Construction" weight="1">Electronic Drafter</item>
    <item name="Construction" weight="1">Elevator Mechanic</item>
    <item name="Construction" weight="1">Excavating Machine Operator</item>
    <item name="Construction" weight="1">Fence Installer</item>
    <item name="Construction" weight="1">Fire Prevention Engineer</item>
    <item name="Construction" weight="1">Fire Protection Engineer</item>
    <item name="Construction" weight="1">Fire Protection Engineering Technician</item>
    <item name="Construction" weight="1">Hardwood Floor Finisher</item>
    <item name="Construction" weight="1">Heating, A/C, &amp; Refrigeration Technician</item>
    <item name="Construction" weight="1">Heavy Equipment Mechanic</item>
    <item name="Construction" weight="1">Home Appliance Installer</item>
    <item name="Construction" weight="1">Home Entertainment System Installer</item>
    <item name="Construction" weight="1">Industrial Painter</item>
    <item name="Construction" weight="1">Insulation Installer</item>
    <item name="Construction" weight="1">Land Surveyor</item>
    <item name="Construction" weight="1">Metal Casting Machine Operator</item>
    <item name="Construction" weight="1">Metal Fabricator</item>
    <item name="Construction" weight="1">Overhead Door Installer</item>
    <item name="Construction" weight="1">Painters, Transportation Equipment</item>
    <item name="Construction" weight="1">Plumber</item>
    <item name="Construction" weight="1">Power-Line Installer and Mechanic</item>
    <item name="Construction" weight="1">Product Safety Engineer</item>
    <item name="Construction" weight="1">Radio Mechanic</item>
    <item name="Construction" weight="1">Safety Inspector</item>
    <item name="Construction" weight="1">Septic Tank and Sewer Servicer</item>
    <item name="Construction" weight="1">Sheet Metal Workers</item>
    <item name="Construction" weight="1">Telecommunications Line Installers and Repairers</item>
    <item name="Construction" weight="1">Telecommunications Maintenance Worker</item>
    <item name="Construction" weight="1">Telecommunications Technician</item>
    <item name="Construction" weight="1">Telephone Station Installers</item>
    <item name="Construction" weight="1">Tile and Marble Setter</item>
    <item name="Construction" weight="1">[=Pick('Bulldozer','Grader')] Operator</item>
    <item name="Construction" weight="1">[=Pick('Gas','Arc','Plasma','Laser')] Welder</item>
    <item name="Construction" weight="1">[=Pick('Plasterers','Stucco')] Mason</item>
    <item name="Education" weight="1">Adult Literacy and Remedial Education Teacher</item>
    <item name="Education" weight="1">Agricultural Sciences Professor</item>
    <item name="Education" weight="1">Alumni Relations Coordinator</item>
    <item name="Education" weight="1">Anthropology and Archeology Professor</item>
    <item name="Education" weight="1">Architecture Professor</item>
    <item name="Education" weight="1">Area, Ethnic, and Cultural Studies Professor</item>
    <item name="Education" weight="1">Athletic Director</item>
    <item name="Education" weight="1">Biology Professor</item>
    <item name="Education" weight="1">Business Professor</item>
    <item name="Education" weight="1">Career Counselor</item>
    <item name="Education" weight="1">Chemistry Professor</item>
    <item name="Education" weight="1">Child Care Worker</item>
    <item name="Education" weight="1">College/University Professor</item>
    <item name="Education" weight="1">Communications Professor</item>
    <item name="Education" weight="1">Computer Science Professor</item>
    <item name="Education" weight="1">Criminal Justice Professor</item>
    <item name="Education" weight="1">Deaf Students Teacher</item>
    <item name="Education" weight="1">Disabled Students Teacher</item>
    <item name="Education" weight="1">Economics Professor</item>
    <item name="Education" weight="1">Education Professor</item>
    <item name="Education" weight="1">Education and Training Administrator</item>
    <item name="Education" weight="1">Educational Administrator</item>
    <item name="Education" weight="1">Educational Psychologist</item>
    <item name="Education" weight="1">Educational Resource Coordinator</item>
    <item name="Education" weight="1">Educational Therapist</item>
    <item name="Education" weight="1">Elementary School Administrator</item>
    <item name="Education" weight="1">Elementary School Teacher</item>
    <item name="Education" weight="1">Employee Training Instructor</item>
    <item name="Education" weight="1">Engineering Professor</item>
    <item name="Education" weight="1">Environmental Science Professor</item>
    <item name="Education" weight="1">Foreign Language Teacher</item>
    <item name="Education" weight="1">Foreign Student Adviser</item>
    <item name="Education" weight="1">Forestry and Conservation Professor</item>
    <item name="Education" weight="1">Geography Professor</item>
    <item name="Education" weight="1">Graduate Teaching Assistant</item>
    <item name="Education" weight="1">Health Educators</item>
    <item name="Education" weight="1">High School Administrator</item>
    <item name="Education" weight="1">High School Guidance Counselor</item>
    <item name="Education" weight="1">High School Teacher</item>
    <item name="Education" weight="1">History Professor</item>
    <item name="Education" weight="1">Home Economics Teacher</item>
    <item name="Education" weight="1">Industrial Entertainment Teacher</item>
    <item name="Education" weight="1">Instructional Coordinators</item>
    <item name="Education" weight="1">Kindergarten Teacher</item>
    <item name="Education" weight="1">Law Professor</item>
    <item name="Education" weight="1">Library Science Professor</item>
    <item name="Education" weight="1">Math Professor</item>
    <item name="Education" weight="1">Mentally Retarded Students Teacher</item>
    <item name="Education" weight="1">Middle School Administrator</item>
    <item name="Education" weight="1">Middle School Guidance Counselor</item>
    <item name="Education" weight="1">Middle School Teacher</item>
    <item name="Education" weight="1">Music Teacher</item>
    <item name="Education" weight="1">Nursing Professor</item>
    <item name="Education" weight="1">Outdoor Education Teacher</item>
    <item name="Education" weight="1">Philosophy and Religion Professor</item>
    <item name="Education" weight="1">Physical Education Instructor</item>
    <item name="Education" weight="1">Physics Professor</item>
    <item name="Education" weight="1">Political Science Professor</item>
    <item name="Education" weight="1">Preschool Administrator</item>
    <item name="Education" weight="1">Preschool Teacher</item>
    <item name="Education" weight="1">Psychology Professor</item>
    <item name="Education" weight="1">Religious Institution Education Coordinator</item>
    <item name="Education" weight="1">Resource Teacher</item>
    <item name="Education" weight="1">Self-Enrichment Education Teacher</item>
    <item name="Education" weight="1">Social Work Professor</item>
    <item name="Education" weight="1">Sociology Professor</item>
    <item name="Education" weight="1">Special Education Administrator</item>
    <item name="Education" weight="1">Student Admissions Administrator</item>
    <item name="Education" weight="1">Student Affairs Administrator</item>
    <item name="Education" weight="1">Student Financial Aid Administrator</item>
    <item name="Education" weight="1">Teacher of the Blind</item>
    <item name="Education" weight="1">Teachers Aide</item>
    <item name="Education" weight="1">Vocational Education Instructor College</item>
    <item name="Education" weight="1">Vocational Education Teacher High School</item>
    <item name="Education" weight="1">Vocational Education Teacher Middle School</item>
    <item name="Education" weight="1">[=Pick('Art','Drama','Music','Dance')] Professor</item>
    <item name="Education" weight="1">[=Pick('English Language','Literature')] Professor</item>
    <item name="Engineering" weight="1">Airport Design Engineer</item>
    <item name="Engineering" weight="1">Biomedical Engineer</item>
    <item name="Engineering" weight="1">Ceramic Engineer</item>
    <item name="Engineering" weight="1">Chemical Engineer</item>
    <item name="Engineering" weight="1">Civil Drafter</item>
    <item name="Engineering" weight="1">Civil Engineer</item>
    <item name="Engineering" weight="1">Civil Engineering Technician</item>
    <item name="Engineering" weight="1">Electrical Engineer</item>
    <item name="Engineering" weight="1">Electronics Engineer</item>
    <item name="Engineering" weight="1">Environmental Engineer</item>
    <item name="Engineering" weight="1">Factory Layout Engineer</item>
    <item name="Engineering" weight="1">Hydraulic Engineer</item>
    <item name="Engineering" weight="1">Irrigation Engineer</item>
    <item name="Engineering" weight="1">Marine Engineer</item>
    <item name="Engineering" weight="1">Mechanical Engineer</item>
    <item name="Engineering" weight="1">Mining Engineer</item>
    <item name="Engineering" weight="1">Nuclear Engineer</item>
    <item name="Engineering" weight="1">Nuclear Fuels Research Engineer</item>
    <item name="Engineering" weight="1">Petroleum Engineer</item>
    <item name="Engineering" weight="1">Photogrammetric Engineer</item>
    <item name="Engineering" weight="1">Quality Control Engineer</item>
    <item name="Engineering" weight="1">Radiation Protection Engineer</item>
    <item name="Engineering" weight="1">Reliability Engineer</item>
    <item name="Engineering" weight="1">Soil Engineer</item>
    <item name="Entertainment" weight="1">Actor</item>
    <item name="Entertainment" weight="1">Aquarium Curator</item>
    <item name="Entertainment" weight="1">Artists [=Pick('Agent','Manager')]</item>
    <item name="Entertainment" weight="1">Athletic Coach</item>
    <item name="Entertainment" weight="1">Athletic Trainer</item>
    <item name="Entertainment" weight="1">Audio-Visual Collections Specialist</item>
    <item name="Entertainment" weight="1">Audiovisual Production Specialist</item>
    <item name="Entertainment" weight="1">Camp Director</item>
    <item name="Entertainment" weight="1">Caption Writer</item>
    <item name="Entertainment" weight="1">Casino Cage Worker</item>
    <item name="Entertainment" weight="1">Casino Cashier</item>
    <item name="Entertainment" weight="1">Casino Dealer</item>
    <item name="Entertainment" weight="1">Casino Floor Person</item>
    <item name="Entertainment" weight="1">Casino Manager</item>
    <item name="Entertainment" weight="1">Casino Pit Boss</item>
    <item name="Entertainment" weight="1">Casino Slot Machine Mechanic</item>
    <item name="Entertainment" weight="1">Casino Surveillance Officer</item>
    <item name="Entertainment" weight="1">Casting Director</item>
    <item name="Entertainment" weight="1">Choreographer</item>
    <item name="Entertainment" weight="1">Copy Writer</item>
    <item name="Entertainment" weight="1">Costume Attendant</item>
    <item name="Entertainment" weight="1">Craft Artist</item>
    <item name="Entertainment" weight="1">Dancer</item>
    <item name="Entertainment" weight="1">Disk Jockey</item>
    <item name="Entertainment" weight="1">Dressing Room Attendant</item>
    <item name="Entertainment" weight="1">Exhibit Artist</item>
    <item name="Entertainment" weight="1">Exhibit Designer</item>
    <item name="Entertainment" weight="1">Fashion Artist</item>
    <item name="Entertainment" weight="1">Fashion Designer</item>
    <item name="Entertainment" weight="1">Fashion Model</item>
    <item name="Entertainment" weight="1">Fine Artist</item>
    <item name="Entertainment" weight="1">Fitness Trainer</item>
    <item name="Entertainment" weight="1">Game Runner</item>
    <item name="Entertainment" weight="1">Makeup Artist</item>
    <item name="Entertainment" weight="1">Motion Picture Director</item>
    <item name="Entertainment" weight="1">Motion Picture Projectionist</item>
    <item name="Entertainment" weight="1">Museum Curator</item>
    <item name="Entertainment" weight="1">Music Director</item>
    <item name="Entertainment" weight="1">Music [=Pick('Arranger','Orchestrator')]</item>
    <item name="Entertainment" weight="1">Musical Instrument Tuner</item>
    <item name="Entertainment" weight="1">Musician</item>
    <item name="Entertainment" weight="1">Printmaker</item>
    <item name="Entertainment" weight="1">Professional Sports Scout</item>
    <item name="Entertainment" weight="1">Props and Lighting Technician</item>
    <item name="Entertainment" weight="1">Recreation Leader</item>
    <item name="Entertainment" weight="1">Recreational Protective Service Worker</item>
    <item name="Entertainment" weight="1">Script Editor</item>
    <item name="Entertainment" weight="1">Singer</item>
    <item name="Entertainment" weight="1">Sound Engineering Technician</item>
    <item name="Entertainment" weight="1">Stained Glass Artist</item>
    <item name="Entertainment" weight="1">Technical [=Pick('Director','Manager')]</item>
    <item name="Entertainment" weight="1">Travel Writer</item>
    <item name="Entertainment" weight="1">Vending Machine Mechanic</item>
    <item name="Entertainment" weight="1">[=Pick('Amusement Park','Recreation')] Attendant</item>
    <item name="Entertainment" weight="1">[=Pick('Radio','TV')] Talk Show Host</item>
    <item name="Entertainment" weight="1">[=Pick('Referee','Umpire')]</item>
    <item name="Entertainment" weight="1">[=Pick('Sport/'s','Entertainment')] [=Pick('Agent','Manager')]</item>
    <item name="Entertainment" weight="1">[=Pick('Usher','Lobby')] Attendant</item>
    <item name="Farming" weight="1">Agricultural Crop Farm Manager</item>
    <item name="Farming" weight="1">Agricultural Engineer</item>
    <item name="Farming" weight="1">Agricultural Equipment Operator</item>
    <item name="Farming" weight="1">Agricultural Inspector</item>
    <item name="Farming" weight="1">Agricultural Product Sorter</item>
    <item name="Farming" weight="1">Agricultural Technician</item>
    <item name="Farming" weight="1">Animal Breeder</item>
    <item name="Farming" weight="1">Animal Husbandry Worker Supervisor</item>
    <item name="Farming" weight="1">Animal Kennel Supervisor</item>
    <item name="Farming" weight="1">Animal Trainer</item>
    <item name="Farming" weight="1">Animal [=Pick('Keeper','Groomer')]</item>
    <item name="Farming" weight="1">Commercial Fisherman</item>
    <item name="Farming" weight="1">Crop Workers Supervisor</item>
    <item name="Farming" weight="1">Dairy Technologist</item>
    <item name="Farming" weight="1">Farm Equipment Mechanic</item>
    <item name="Farming" weight="1">Farm Hand</item>
    <item name="Farming" weight="1">Farm Labor Contractor</item>
    <item name="Farming" weight="1">Farm Manager</item>
    <item name="Farming" weight="1">Farm Products Purchasing Agent</item>
    <item name="Farming" weight="1">Farmworker</item>
    <item name="Farming" weight="1">Fish Hatchery Specialist</item>
    <item name="Farming" weight="1">Fishery Worker Supervisor</item>
    <item name="Farming" weight="1">Forest Engineer</item>
    <item name="Farming" weight="1">Forest Fire Inspector</item>
    <item name="Farming" weight="1">Forest Fire Prevention Supervisor</item>
    <item name="Farming" weight="1">Forest and Conservation Technician</item>
    <item name="Farming" weight="1">Greenhouse and Nursery Manager</item>
    <item name="Farming" weight="1">Livestock Commission Agent</item>
    <item name="Farming" weight="1">Log Grader and Scaler</item>
    <item name="Farming" weight="1">Logging Tractor Operator</item>
    <item name="Farming" weight="1">Logging Worker Supervisor</item>
    <item name="Farming" weight="1">Nursery Worker</item>
    <item name="Farming" weight="1">Park Naturalist</item>
    <item name="Farming" weight="1">Plant Breeder</item>
    <item name="Farming" weight="1">Range Manager</item>
    <item name="Farming" weight="1">Soil Conservation Technician</item>
    <item name="Farming" weight="1">Soil Conservationist</item>
    <item name="Farming" weight="1">Wildlife Control Agent</item>
    <item name="Farming" weight="1">[=Pick('Farmer','Rancher')]</item>
    <item name="Finance" weight="1">ATM Machine Servicer</item>
    <item name="Finance" weight="1">Accounting Specialist</item>
    <item name="Finance" weight="1">Adjustment Clerk</item>
    <item name="Finance" weight="1">Advertising Account Executive</item>
    <item name="Finance" weight="1">Bank Examiner</item>
    <item name="Finance" weight="1">Bank Teller</item>
    <item name="Finance" weight="1">Billing Specialist</item>
    <item name="Finance" weight="1">Broker's Floor Representative</item>
    <item name="Finance" weight="1">Brokerage Clerk</item>
    <item name="Finance" weight="1">Budget Accountant</item>
    <item name="Finance" weight="1">Budget Analyst</item>
    <item name="Finance" weight="1">Certified Public Accountant</item>
    <item name="Finance" weight="1">Controller</item>
    <item name="Finance" weight="1">Correspondence Clerk</item>
    <item name="Finance" weight="1">Cost Accountant</item>
    <item name="Finance" weight="1">Credit Adjuster</item>
    <item name="Finance" weight="1">Credit Analyst</item>
    <item name="Finance" weight="1">Credit Reporter</item>
    <item name="Finance" weight="1">Finance Manager</item>
    <item name="Finance" weight="1">Financial Aid Counselor</item>
    <item name="Finance" weight="1">Financial Analyst</item>
    <item name="Finance" weight="1">Financial Examiner</item>
    <item name="Finance" weight="1">Financial Planner</item>
    <item name="Finance" weight="1">Financial Services Sales Agent</item>
    <item name="Finance" weight="1">Foreign Exchange Trader</item>
    <item name="Finance" weight="1">Fund Raiser</item>
    <item name="Finance" weight="1">Funds Development Administrator</item>
    <item name="Finance" weight="1">Home Economist</item>
    <item name="Finance" weight="1">Insurance Adjuster</item>
    <item name="Finance" weight="1">Insurance Agent</item>
    <item name="Finance" weight="1">Insurance Appraiser</item>
    <item name="Finance" weight="1">Insurance Claim Examiner</item>
    <item name="Finance" weight="1">Insurance Claims Adjuster</item>
    <item name="Finance" weight="1">Insurance Claims Clerks</item>
    <item name="Finance" weight="1">Insurance Estate Planner</item>
    <item name="Finance" weight="1">Insurance Policy Processing Clerk</item>
    <item name="Finance" weight="1">Insurance Underwriter</item>
    <item name="Finance" weight="1">Internal Auditor</item>
    <item name="Finance" weight="1">Loan Counselor</item>
    <item name="Finance" weight="1">Loan Interviewers and Clerks</item>
    <item name="Finance" weight="1">Loan Officer</item>
    <item name="Finance" weight="1">Medical Insurance Claims Analyst</item>
    <item name="Finance" weight="1">New Accounts Clerk</item>
    <item name="Finance" weight="1">Property Accountant</item>
    <item name="Finance" weight="1">Property Assessor</item>
    <item name="Finance" weight="1">Real Estate Sales Agent</item>
    <item name="Finance" weight="1">Securities Broker</item>
    <item name="Finance" weight="1">Systems Accountant</item>
    <item name="Finance" weight="1">Tax Accountant</item>
    <item name="Finance" weight="1">Tax Auditor</item>
    <item name="Finance" weight="1">Tax Examiner</item>
    <item name="Finance" weight="1">Tax Preparer</item>
    <item name="Finance" weight="1">[=Pick('Bank','Branch')] Manager</item>
    <item name="Food" weight="1">Baker</item>
    <item name="Food" weight="1">Barista</item>
    <item name="Food" weight="1">Bartender</item>
    <item name="Food" weight="1">Bus Boy / Bus Girl</item>
    <item name="Food" weight="1">Chef</item>
    <item name="Food" weight="1">Cook</item>
    <item name="Food" weight="1">Dishwasher</item>
    <item name="Food" weight="1">Food Batchmaker</item>
    <item name="Food" weight="1">Food Preparation Worker</item>
    <item name="Food" weight="1">Food Science Technician</item>
    <item name="Food" weight="1">Food Technologist</item>
    <item name="Food" weight="1">Host</item>
    <item name="Food" weight="1">Hotel Convention/Events Coordinator</item>
    <item name="Food" weight="1">Hotel Manager</item>
    <item name="Food" weight="1">Restaurant Food Coordinator</item>
    <item name="Food" weight="1">Waiter</item>
    <item name="Food" weight="1">[=Pick('Baggage Porter','Bellhop')]</item>
    <item name="Food" weight="1">[=Pick('Counter','Rental')] Clerks</item>
    <item name="Food" weight="1">[=Pick('Hotel','Motel')] Desk Clerk</item>
    <item name="Government" weight="1">Administrative Law Judge</item>
    <item name="Government" weight="1">Administrative Service Manager</item>
    <item name="Government" weight="1">Aeronautical &amp; Aerospace Engineer</item>
    <item name="Government" weight="1">Aerospace Engineering Technician</item>
    <item name="Government" weight="1">Air Traffic Controller</item>
    <item name="Government" weight="1">Aircraft Mechanic</item>
    <item name="Government" weight="1">Airfield Operations Specialist</item>
    <item name="Government" weight="1">Ambulance Driver</item>
    <item name="Government" weight="1">Animal Control Worker</item>
    <item name="Government" weight="1">Anti-Terrorism Intelligence Agent</item>
    <item name="Government" weight="1">Armored Assault Vehicle Crew Member</item>
    <item name="Government" weight="1">Armored Assault Vehicle Officer</item>
    <item name="Government" weight="1">Artillery and Missile Crew Member</item>
    <item name="Government" weight="1">Artillery and Missile Officer</item>
    <item name="Government" weight="1">Ballistics Expert</item>
    <item name="Government" weight="1">Border Patrol Agent</item>
    <item name="Government" weight="1">Bridge and Lock Tender</item>
    <item name="Government" weight="1">Bus Driver</item>
    <item name="Government" weight="1">Child Support Investigator</item>
    <item name="Government" weight="1">Child Support Services Worker</item>
    <item name="Government" weight="1">City Planning Aide</item>
    <item name="Government" weight="1">Community Organization Worker</item>
    <item name="Government" weight="1">Community Welfare Worker</item>
    <item name="Government" weight="1">Congressional Aide</item>
    <item name="Government" weight="1">Correction Officer</item>
    <item name="Government" weight="1">Court Administrator</item>
    <item name="Government" weight="1">Court Clerk</item>
    <item name="Government" weight="1">Court Reporter</item>
    <item name="Government" weight="1">Criminal Investigator (Detective)</item>
    <item name="Government" weight="1">Criminal Lawyer</item>
    <item name="Government" weight="1">Customs Inspector</item>
    <item name="Government" weight="1">Deputy Sheriff</item>
    <item name="Government" weight="1">Equal Opportunity Representative</item>
    <item name="Government" weight="1">Family Caseworker</item>
    <item name="Government" weight="1">Fire Inspector</item>
    <item name="Government" weight="1">Fire Investigator</item>
    <item name="Government" weight="1">Fire Prevention Engineer</item>
    <item name="Government" weight="1">Fire Protection Engineer</item>
    <item name="Government" weight="1">Fire Protection Engineering Technician</item>
    <item name="Government" weight="1">Firefighter</item>
    <item name="Government" weight="1">Fish &amp; Game Warden</item>
    <item name="Government" weight="1">Food &amp; Drug Inspector</item>
    <item name="Government" weight="1">Foreign Service Officer</item>
    <item name="Government" weight="1">Foreign Service Peacekeeping Specialist</item>
    <item name="Government" weight="1">Forensic Science Technician</item>
    <item name="Government" weight="1">Forensics Psychologist</item>
    <item name="Government" weight="1">Forest Fire Inspector</item>
    <item name="Government" weight="1">Forest Fire Prevention Supervisor</item>
    <item name="Government" weight="1">Fraud Investigator</item>
    <item name="Government" weight="1">Government Budget Analyst</item>
    <item name="Government" weight="1">Government Property Inspectors</item>
    <item name="Government" weight="1">Government Service Executives</item>
    <item name="Government" weight="1">Harbor, Lake &amp; Waterways Police</item>
    <item name="Government" weight="1">Hearing Officer</item>
    <item name="Government" weight="1">Highway Maintenance Worker</item>
    <item name="Government" weight="1">Highway Patrol Pilot</item>
    <item name="Government" weight="1">Historic Site Administrator</item>
    <item name="Government" weight="1">Immigration Inspector</item>
    <item name="Government" weight="1">Infantry Officers</item>
    <item name="Government" weight="1">Instructor, Police-Canine Services</item>
    <item name="Government" weight="1">Intelligence Specialist</item>
    <item name="Government" weight="1">Law Clerk</item>
    <item name="Government" weight="1">Legislative Assistant</item>
    <item name="Government" weight="1">Legislator</item>
    <item name="Government" weight="1">Library Assistant</item>
    <item name="Government" weight="1">Library Consultant</item>
    <item name="Government" weight="1">Library Technician</item>
    <item name="Government" weight="1">License Clerk</item>
    <item name="Government" weight="1">Licensing Examiner</item>
    <item name="Government" weight="1">Marine and Aquatic Biologist</item>
    <item name="Government" weight="1">Medical Examiner/Coroner</item>
    <item name="Government" weight="1">Military Analyst</item>
    <item name="Government" weight="1">Military Control Center Specialist</item>
    <item name="Government" weight="1">Military Officer</item>
    <item name="Government" weight="1">Military-Enlisted Personnel</item>
    <item name="Government" weight="1">Missing Person Investigator</item>
    <item name="Government" weight="1">Municipal Fire Fighting Supervisor</item>
    <item name="Government" weight="1">Narcotics Investigator</item>
    <item name="Government" weight="1">Occupational Safety &amp; Health Inspector</item>
    <item name="Government" weight="1">Park Naturalist</item>
    <item name="Government" weight="1">Parking Enforcement Officer</item>
    <item name="Government" weight="1">Parole Officer</item>
    <item name="Government" weight="1">Patent Agent</item>
    <item name="Government" weight="1">Police Artist</item>
    <item name="Government" weight="1">Police Identification and Records Officer</item>
    <item name="Government" weight="1">Police Officer</item>
    <item name="Government" weight="1">Police and Detectives Supervisor</item>
    <item name="Government" weight="1">Political Scientist</item>
    <item name="Government" weight="1">Postal Service Clerks</item>
    <item name="Government" weight="1">Postal Service Mail Carrier</item>
    <item name="Government" weight="1">Postal Service Mail Sorter</item>
    <item name="Government" weight="1">Probate Lawyer</item>
    <item name="Government" weight="1">Probation Officer</item>
    <item name="Government" weight="1">Range Manager</item>
    <item name="Government" weight="1">Revenue Agent</item>
    <item name="Government" weight="1">Sheriff</item>
    <item name="Government" weight="1">Social Welfare Administrator</item>
    <item name="Government" weight="1">Social Worker</item>
    <item name="Government" weight="1">Soil Conservation Technician</item>
    <item name="Government" weight="1">Soil Conservationist</item>
    <item name="Government" weight="1">Special Forces Officers</item>
    <item name="Government" weight="1">Special Forces</item>
    <item name="Government" weight="1">Tax Auditor</item>
    <item name="Government" weight="1">Tax Collector</item>
    <item name="Government" weight="1">Tax Examiner</item>
    <item name="Government" weight="1">Town Clerk</item>
    <item name="Government" weight="1">Traffic Technician</item>
    <item name="Government" weight="1">Transit and Railroad Police</item>
    <item name="Government" weight="1">Transportation Security Screener</item>
    <item name="Government" weight="1">Transportation Systems Design Engineer</item>
    <item name="Government" weight="1">Unemployment Inspector</item>
    <item name="Government" weight="1">Urban and Regional Planner</item>
    <item name="Government" weight="1">Water Pollution Control Inspector</item>
    <item name="Government" weight="1">Welfare Eligibility Worker</item>
    <item name="Government" weight="1">Wildlife Biologist</item>
    <item name="Government" weight="1">Word Processing Specialist</item>
    <item name="Government" weight="1">Zoologist</item>
    <item name="Government" weight="1">[=Pick('County','City')] Auditor</item>
    <item name="Government" weight="1">[=Pick('Postmaster','Mail Superintendent')]</item>
    <item name="Government" weight="1">[=Pick('Social','Community')] Service Manager</item>
    <item name="Government" weight="1">[=Pick('Subway','Streetcar')] Conductor</item>
    <item name="Health" weight="1">Alcohol &amp; Drug Abuse Assistance Coordinator</item>
    <item name="Health" weight="1">Ambulance Driver</item>
    <item name="Health" weight="1">Anesthesiologist (MD)</item>
    <item name="Health" weight="1">Art Therapist</item>
    <item name="Health" weight="1">Cardiologist (MD)</item>
    <item name="Health" weight="1">Cardiopulmonary Technologist</item>
    <item name="Health" weight="1">Clinical Dietitian</item>
    <item name="Health" weight="1">Clinical Psychologist</item>
    <item name="Health" weight="1">Clinical Sociologist</item>
    <item name="Health" weight="1">Community Health Nurse</item>
    <item name="Health" weight="1">Counseling Psychologist</item>
    <item name="Health" weight="1">Dental Assistant</item>
    <item name="Health" weight="1">Dental Hygienist</item>
    <item name="Health" weight="1">Dental Laboratory Technician</item>
    <item name="Health" weight="1">Dentist (MD)</item>
    <item name="Health" weight="1">Dermatologist (MD)</item>
    <item name="Health" weight="1">Developmental Psychologist</item>
    <item name="Health" weight="1">Dietetic Technician</item>
    <item name="Health" weight="1">EEG Technician</item>
    <item name="Health" weight="1">Emergency Medical Technician</item>
    <item name="Health" weight="1">Exercise Physiologist</item>
    <item name="Health" weight="1">Experimental Psychologist</item>
    <item name="Health" weight="1">Family Practitioner (MD)</item>
    <item name="Health" weight="1">Field Health Officer</item>
    <item name="Health" weight="1">General Internists (MD)</item>
    <item name="Health" weight="1">Gynecologist (MD)</item>
    <item name="Health" weight="1">Health Care Facilities Inspector</item>
    <item name="Health" weight="1">Health Case Manager</item>
    <item name="Health" weight="1">Health Psychologist</item>
    <item name="Health" weight="1">Home Health Aide</item>
    <item name="Health" weight="1">Home Health Technician</item>
    <item name="Health" weight="1">Hospital Administrator</item>
    <item name="Health" weight="1">Hospital Nurse</item>
    <item name="Health" weight="1">Human Factors Psychologist</item>
    <item name="Health" weight="1">Industrial Health Engineer</item>
    <item name="Health" weight="1">Industrial Therapist</item>
    <item name="Health" weight="1">Industrial-Organizational Psychologist</item>
    <item name="Health" weight="1">Licensed Practical Nurse (LPN)</item>
    <item name="Health" weight="1">Manual Entertainment Therapist</item>
    <item name="Health" weight="1">Massage Therapist</item>
    <item name="Health" weight="1">Medical Administrative Assistant</item>
    <item name="Health" weight="1">Medical Appliance Technician</item>
    <item name="Health" weight="1">Medical Assistant</item>
    <item name="Health" weight="1">Medical Equipment Preparer</item>
    <item name="Health" weight="1">Medical Laboratory Technician</item>
    <item name="Health" weight="1">Medical Photographer</item>
    <item name="Health" weight="1">Medical Records Administrator</item>
    <item name="Health" weight="1">Medical Records Technician</item>
    <item name="Health" weight="1">Medical Secretary</item>
    <item name="Health" weight="1">Medical Technologist</item>
    <item name="Health" weight="1">Medical and Public Health Social Worker</item>
    <item name="Health" weight="1">Medical and Scientific Illustrator</item>
    <item name="Health" weight="1">Mental Health Counselor</item>
    <item name="Health" weight="1">Music Therapist</item>
    <item name="Health" weight="1">Nurse Practitioner</item>
    <item name="Health" weight="1">Nurse's Aide</item>
    <item name="Health" weight="1">Obstetrician (MD)</item>
    <item name="Health" weight="1">Occupational Analyst</item>
    <item name="Health" weight="1">Occupational Physician (MD)</item>
    <item name="Health" weight="1">Occupational Therapist</item>
    <item name="Health" weight="1">Occupational Therapy Assistant</item>
    <item name="Health" weight="1">Ophthalmic Laboratory Technician</item>
    <item name="Health" weight="1">Ophthalmologist (MD)</item>
    <item name="Health" weight="1">Orthodontic Assistant</item>
    <item name="Health" weight="1">Orthodontic Laboratory Technician</item>
    <item name="Health" weight="1">Orthodontist (MD)</item>
    <item name="Health" weight="1">Pathologist (MD)</item>
    <item name="Health" weight="1">Pediatric Dentist</item>
    <item name="Health" weight="1">Pediatrician (MD)</item>
    <item name="Health" weight="1">Pharmacy Aide</item>
    <item name="Health" weight="1">Pharmacy Technician</item>
    <item name="Health" weight="1">Physical Therapist Aide</item>
    <item name="Health" weight="1">Physical Therapist</item>
    <item name="Health" weight="1">Physical Therapy Assistant</item>
    <item name="Health" weight="1">Physician's Assistant (PA)</item>
    <item name="Health" weight="1">Physician's Office Nurse</item>
    <item name="Health" weight="1">Plastic Surgeon</item>
    <item name="Health" weight="1">Private Nurse</item>
    <item name="Health" weight="1">Prosthetic Technician</item>
    <item name="Health" weight="1">Psychiatric Aide</item>
    <item name="Health" weight="1">Psychiatric Technician</item>
    <item name="Health" weight="1">Psychiatrist (MD)</item>
    <item name="Health" weight="1">Public Health Service Officer</item>
    <item name="Health" weight="1">Radiation Therapists</item>
    <item name="Health" weight="1">Radiologic Technician</item>
    <item name="Health" weight="1">Radiologic Technologist</item>
    <item name="Health" weight="1">Radiologist (MD)</item>
    <item name="Health" weight="1">Recreational Therapist</item>
    <item name="Health" weight="1">Residence Counselor</item>
    <item name="Health" weight="1">Respiratory Care Technician</item>
    <item name="Health" weight="1">Respiratory Therapist</item>
    <item name="Health" weight="1">Respiratory Therapy Technician</item>
    <item name="Health" weight="1">School Nurse</item>
    <item name="Health" weight="1">School Psychologist</item>
    <item name="Health" weight="1">Social Psychologist</item>
    <item name="Health" weight="1">Social Service Volunteer</item>
    <item name="Health" weight="1">Speech Pathologist</item>
    <item name="Health" weight="1">Sport Psychologist</item>
    <item name="Health" weight="1">Sports Physician (Orthopedist)</item>
    <item name="Health" weight="1">Substance Abuse Counselor</item>
    <item name="Health" weight="1">Surgeons (MD)</item>
    <item name="Health" weight="1">Surgical Technician/Technologist</item>
    <item name="Health" weight="1">Ultrasound Technologist</item>
    <item name="Health" weight="1">Veterinarian (VMD)</item>
    <item name="Health" weight="1">Veterinarian Technician</item>
    <item name="Health" weight="1">Veterinary Assistant</item>
    <item name="Health" weight="1">Vocational Rehabilitation Counselor</item>
    <item name="Health" weight="1">Voice Pathologist</item>
    <item name="Health" weight="1">Zoo Veterinarian</item>
    <item name="Health" weight="1">[=Pick('Dental','Orthodontic')] Office Administrator</item>
    <item name="Health" weight="1">[=Pick('Dietitian','Nutritionist')]</item>
    <item name="Health" weight="1">[=Pick('Marriage','Family')] Therapist</item>
    <item name="Health" weight="1">[=Pick('Oral','Maxillofacial')] Surgeon</item>
    <item name="HumanResources" weight="1">Employee Benefits Analyst</item>
    <item name="HumanResources" weight="1">Employment Interviewer</item>
    <item name="HumanResources" weight="1">Employment and Placement Specialist</item>
    <item name="HumanResources" weight="1">Human Resources Management Advisor</item>
    <item name="HumanResources" weight="1">Human Resources Management Consultant</item>
    <item name="HumanResources" weight="1">Job Analyst</item>
    <item name="HumanResources" weight="1">Job Development Specialist</item>
    <item name="HumanResources" weight="1">Labor Relations Advisor</item>
    <item name="HumanResources" weight="1">Payroll and Timekeeping Clerk</item>
    <item name="HumanResources" weight="1">Personnel Administrator</item>
    <item name="HumanResources" weight="1">Personnel Assistant</item>
    <item name="HumanResources" weight="1">Personnel Recruiter</item>
    <item name="HumanResources" weight="1">Social and Human Service Assistant</item>
    <item name="Legal" weight="1">Admiralty Lawyer</item>
    <item name="Legal" weight="1">Appeals Referee</item>
    <item name="Legal" weight="1">Corporation Lawyer</item>
    <item name="Legal" weight="1">Legal Assistant</item>
    <item name="Legal" weight="1">Legal Secretary</item>
    <item name="Legal" weight="1">Patent Lawyer</item>
    <item name="Legal" weight="1">Tax Lawyer</item>
    <item name="Legal" weight="1">Title Examiner</item>
    <item name="Legal" weight="1">Title Searchers</item>
    <item name="Management" weight="1">Airport Administrator</item>
    <item name="Management" weight="1">Benefits Manager</item>
    <item name="Management" weight="1">Catering Administrator</item>
    <item name="Management" weight="1">Child Care Center Administrator</item>
    <item name="Management" weight="1">Compensation Administrator</item>
    <item name="Management" weight="1">Computer and Information Systems Manager</item>
    <item name="Management" weight="1">Contract Administrator</item>
    <item name="Management" weight="1">Customer Service Supervisor</item>
    <item name="Management" weight="1">Emergency Management Specialist</item>
    <item name="Management" weight="1">Employment Administrator</item>
    <item name="Management" weight="1">Engineering Manager</item>
    <item name="Management" weight="1">Excavating Supervisor</item>
    <item name="Management" weight="1">Harbor Master</item>
    <item name="Management" weight="1">Horticultural Worker Supervisor</item>
    <item name="Management" weight="1">IT Administrator</item>
    <item name="Management" weight="1">Maintenance Supervisor</item>
    <item name="Management" weight="1">Management [=Pick('Consultant','Analyst')]</item>
    <item name="Management" weight="1">Marina Boat Charter Administrator</item>
    <item name="Management" weight="1">Marketing Manager</item>
    <item name="Management" weight="1">Office Supervisor</item>
    <item name="Management" weight="1">Operations Management Analyst</item>
    <item name="Management" weight="1">Personal Service Supervisor</item>
    <item name="Management" weight="1">Property Manager</item>
    <item name="Management" weight="1">Public Relations Manager</item>
    <item name="Management" weight="1">Purchasing Manager</item>
    <item name="Management" weight="1">Registrar Administrator</item>
    <item name="Management" weight="1">Restaurant Manager</item>
    <item name="Management" weight="1">Retail Sales Department Supervisor</item>
    <item name="Management" weight="1">Retail Store Manager</item>
    <item name="Management" weight="1">Sales Manager</item>
    <item name="Management" weight="1">Sports Events Business Manager</item>
    <item name="Management" weight="1">Storage and Distribution Manager</item>
    <item name="Management" weight="1">[=Pick('General','Operation')] Manager</item>
    <item name="Manager" weight="1">Non-Retail Sales Supervisor</item>
    <item name="Manufacturing" weight="1">Aircraft Assembler</item>
    <item name="Manufacturing" weight="1">Automotive Engineer</item>
    <item name="Manufacturing" weight="1">Bindery Machine Set-Up Operator</item>
    <item name="Manufacturing" weight="1">Bindery Machine Tender</item>
    <item name="Manufacturing" weight="1">Biological Technician</item>
    <item name="Manufacturing" weight="1">Biomedical Equipment Technician</item>
    <item name="Manufacturing" weight="1">Boat Builder</item>
    <item name="Manufacturing" weight="1">Chemical Equipment Operator</item>
    <item name="Manufacturing" weight="1">Chemical Plant Operator</item>
    <item name="Manufacturing" weight="1">Chemical Technician</item>
    <item name="Manufacturing" weight="1">Computer Aided Design (CAD) Technician</item>
    <item name="Manufacturing" weight="1">Computer Controlled Machine Tool Operator</item>
    <item name="Manufacturing" weight="1">Die Cutter Operator</item>
    <item name="Manufacturing" weight="1">Electric Motor Mechanic</item>
    <item name="Manufacturing" weight="1">Electrical PEntertainment Re-conditioner</item>
    <item name="Manufacturing" weight="1">Electrical Technician</item>
    <item name="Manufacturing" weight="1">Electro-Mechanical Technician</item>
    <item name="Manufacturing" weight="1">Electromechanical Equipment Assembler</item>
    <item name="Manufacturing" weight="1">Electronics Technician</item>
    <item name="Manufacturing" weight="1">Engine and Machine Assemblers</item>
    <item name="Manufacturing" weight="1">Forging Machine Operator</item>
    <item name="Manufacturing" weight="1">Gluing Machine Operator</item>
    <item name="Manufacturing" weight="1">Graphic Entertainment Job Printer</item>
    <item name="Manufacturing" weight="1">Hand Sewer</item>
    <item name="Manufacturing" weight="1">Hand and Portable Tool Mechanic</item>
    <item name="Manufacturing" weight="1">Industrial Designer</item>
    <item name="Manufacturing" weight="1">Industrial Engineer</item>
    <item name="Manufacturing" weight="1">Industrial Engineering Technician</item>
    <item name="Manufacturing" weight="1">Industrial Hygienist</item>
    <item name="Manufacturing" weight="1">Industrial Machinery Mechanic</item>
    <item name="Manufacturing" weight="1">Industrial Waste Inspector</item>
    <item name="Manufacturing" weight="1">Instrument Technician</item>
    <item name="Manufacturing" weight="1">Lathe Operator</item>
    <item name="Manufacturing" weight="1">Machine [=Pick('Feeder','Off-bearer')]</item>
    <item name="Manufacturing" weight="1">Manufacturing Plant Manager</item>
    <item name="Manufacturing" weight="1">Marine Drafter</item>
    <item name="Manufacturing" weight="1">Materials Engineer</item>
    <item name="Manufacturing" weight="1">Materials Inspector</item>
    <item name="Manufacturing" weight="1">Materials Scientist</item>
    <item name="Manufacturing" weight="1">Meat Packer</item>
    <item name="Manufacturing" weight="1">Meat, Poultry, and Fish Trimmer</item>
    <item name="Manufacturing" weight="1">Mechanical Drafter</item>
    <item name="Manufacturing" weight="1">Mechanical Engineering Technician</item>
    <item name="Manufacturing" weight="1">Mill Worker</item>
    <item name="Manufacturing" weight="1">Motorboat Mechanic</item>
    <item name="Manufacturing" weight="1">Motorcycle Mechanic</item>
    <item name="Manufacturing" weight="1">Numerical Tool Programmer</item>
    <item name="Manufacturing" weight="1">Operating Engineers</item>
    <item name="Manufacturing" weight="1">Order Clerk</item>
    <item name="Manufacturing" weight="1">Order Filler</item>
    <item name="Manufacturing" weight="1">Package Designer</item>
    <item name="Manufacturing" weight="1">Paste-Up Worker</item>
    <item name="Manufacturing" weight="1">Petroleum Refinery Operator</item>
    <item name="Manufacturing" weight="1">Petroleum Technician</item>
    <item name="Manufacturing" weight="1">Photo-Optics Technician</item>
    <item name="Manufacturing" weight="1">Photoengravers</item>
    <item name="Manufacturing" weight="1">Photographic Equipment Mechanic</item>
    <item name="Manufacturing" weight="1">Photographic Process Workers</item>
    <item name="Manufacturing" weight="1">Power Plant Operators</item>
    <item name="Manufacturing" weight="1">Product Planner</item>
    <item name="Manufacturing" weight="1">Production Planner</item>
    <item name="Manufacturing" weight="1">Production, Planning, and Expediting Clerk</item>
    <item name="Manufacturing" weight="1">Quality Control Coordinator</item>
    <item name="Manufacturing" weight="1">Quality Control Inspector</item>
    <item name="Manufacturing" weight="1">Quality Control Technician</item>
    <item name="Manufacturing" weight="1">Recreational Vehicle Mechanic</item>
    <item name="Manufacturing" weight="1">Sawing Machine Operator</item>
    <item name="Manufacturing" weight="1">Scanner Operator</item>
    <item name="Manufacturing" weight="1">Screen Printing Machine Operator</item>
    <item name="Manufacturing" weight="1">Sewing Machine Operator</item>
    <item name="Manufacturing" weight="1">Ship Carpenter</item>
    <item name="Manufacturing" weight="1">Shoe Machine Operator</item>
    <item name="Manufacturing" weight="1">Small Engine Mechanics</item>
    <item name="Manufacturing" weight="1">Solar Energy Systems Designer</item>
    <item name="Manufacturing" weight="1">Standards Engineer</item>
    <item name="Manufacturing" weight="1">Steel Worker</item>
    <item name="Manufacturing" weight="1">Structural Drafter</item>
    <item name="Manufacturing" weight="1">Structural Engineer</item>
    <item name="Manufacturing" weight="1">Textile Bleaching and Dyeing Machine Operator</item>
    <item name="Manufacturing" weight="1">Textile Cutting Machine Operator</item>
    <item name="Manufacturing" weight="1">Tool &amp; Machine Designer</item>
    <item name="Manufacturing" weight="1">Tool Grinder, Filer, and Sharpener</item>
    <item name="Manufacturing" weight="1">Tool and Die Maker</item>
    <item name="Manufacturing" weight="1">Woodworking Machine Operator</item>
    <item name="Manufacturing" weight="1">[=Pick('Printing','Graphic Entertainment')] Reproduction Technician</item>
    <item name="Manufacturing" weight="1">[=Pick('Shipping','Receiving','Traffic')] Clerk</item>
    <item name="Mariner" weight="1">Able Seamen</item>
    <item name="Mariner" weight="1">Marine Architect</item>
    <item name="Mariner" weight="1">Marine Cargo Surveyor</item>
    <item name="Mariner" weight="1">Marine Surveyor</item>
    <item name="Mariner" weight="1">Oceanographic Assistant</item>
    <item name="Mariner" weight="1">Ordinary Seamen</item>
    <item name="Media" weight="1">Advertising Agency Coordinator</item>
    <item name="Media" weight="1">Broadcast News Analyst</item>
    <item name="Media" weight="1">Broadcast Technician</item>
    <item name="Media" weight="1">Newspaper Editor</item>
    <item name="Media" weight="1">Publication Editor</item>
    <item name="Media" weight="1">Radio Operator</item>
    <item name="Media" weight="1">Technical &amp; Scientific Publication Editor</item>
    <item name="Media" weight="1">Technical Publication Writer</item>
    <item name="Media" weight="1">Video Engineer</item>
    <item name="Media" weight="1">[=Pick('Newspaper','Magazine')] Writer</item>
    <item name="Media" weight="1">[=Pick('Newspaper','Magazine')]Editorial Writer</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] Announcer</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] News Commentator</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] Newscaster</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] Producer</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] Program Director</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] Sports Announcer</item>
    <item name="Media" weight="1">[=Pick('Radio','TV')] Station Administrator</item>
    <item name="Mining" weight="1">Brattice Builder</item>
    <item name="Mining" weight="1">Environmental Planner</item>
    <item name="Mining" weight="1">Explosives Worker</item>
    <item name="Mining" weight="1">Gas Plant Operator</item>
    <item name="Mining" weight="1">Geological Data Technician</item>
    <item name="Mining" weight="1">Geological Technician</item>
    <item name="Mining" weight="1">Mine Cutting Machine Operator</item>
    <item name="Mining" weight="1">Mine Inspector</item>
    <item name="Mining" weight="1">Mining Machine Operator</item>
    <item name="Mining" weight="1">Mining Shovel Machine Operator</item>
    <item name="Mining" weight="1">Petroleum Geologist</item>
    <item name="Mining" weight="1">Petroleum Laboratory Assistant</item>
    <item name="Mining" weight="1">Quarry Worker</item>
    <item name="RealEstate" weight="1">Real Estate Appraiser</item>
    <item name="RealEstate" weight="1">Real Estate Assessor</item>
    <item name="RealEstate" weight="1">Real Estate Broker</item>
    <item name="RealEstate" weight="1">Real Estate Lawyer</item>
    <item name="Retail" weight="1">Door To Door Salesmen</item>
    <item name="Retail" weight="1">Merchandise Displayer</item>
    <item name="Retail" weight="1">Purchasing Agent</item>
    <item name="Retail" weight="1">Retail Buyer</item>
    <item name="Retail" weight="1">Retail Customer Service Representative</item>
    <item name="Retail" weight="1">Retail Inventory Control Analyst</item>
    <item name="Retail" weight="1">Retail Salespersons</item>
    <item name="Retail" weight="1">Sales Floor Stock Clerk</item>
    <item name="Retail" weight="1">Sales Representative</item>
    <item name="Retail" weight="1">Wholesale Buyers</item>
    <item name="Science" weight="1">Animal Scientist</item>
    <item name="Science" weight="1">Aquaculturist</item>
    <item name="Science" weight="1">Atmospheric and Space Scientist</item>
    <item name="Science" weight="1">Cartographer</item>
    <item name="Science" weight="1">Cartographic Technician</item>
    <item name="Science" weight="1">Computer Applications Engineer</item>
    <item name="Science" weight="1">Computer Customer Support Specialist</item>
    <item name="Science" weight="1">Computer Hardware Technician</item>
    <item name="Science" weight="1">Computer Programmer</item>
    <item name="Science" weight="1">Computer Scientist</item>
    <item name="Science" weight="1">Computer Security Specialist</item>
    <item name="Science" weight="1">Computer Software Engineer</item>
    <item name="Science" weight="1">Computer Software Technician</item>
    <item name="Science" weight="1">Computer Systems Engineer</item>
    <item name="Science" weight="1">Conservation Scientist</item>
    <item name="Science" weight="1">Database Administrator</item>
    <item name="Science" weight="1">Horticulturist</item>
    <item name="Science" weight="1">Marine and Aquatic Biologist</item>
    <item name="Science" weight="1">Scientific Linguist</item>
    <item name="Science" weight="1">Scientific Photographer</item>
    <item name="Science" weight="1">Social Science Research Assistants</item>
    <item name="Science" weight="1">Soil Scientist</item>
    <item name="Science" weight="1">Survey Researchers</item>
    <item name="Science" weight="1">Wildlife Biologist</item>
    <item name="Science" weight="1">Zoologist</item>
    <item name="Service" weight="1">Airline Flight Attendant</item>
    <item name="Service" weight="1">Answering Service Operator</item>
    <item name="Service" weight="1">Automobile Mechanic</item>
    <item name="Service" weight="1">Automotive Body Repairer</item>
    <item name="Service" weight="1">Automotive Glass Installer</item>
    <item name="Service" weight="1">Bicycle Mechanic</item>
    <item name="Service" weight="1">Bus and Truck Mechanics</item>
    <item name="Service" weight="1">Communication Equipment Mechanic</item>
    <item name="Service" weight="1">Cosmetologist (Hair Stylist)</item>
    <item name="Service" weight="1">Couriers and Messengers</item>
    <item name="Service" weight="1">Custom Tailor</item>
    <item name="Service" weight="1">Delivery Driver</item>
    <item name="Service" weight="1">Directory Assistance Operator</item>
    <item name="Service" weight="1">Export Agent</item>
    <item name="Service" weight="1">Foreign Language Interpreter</item>
    <item name="Service" weight="1">Foreign Language Translator</item>
    <item name="Service" weight="1">Funeral Attendant</item>
    <item name="Service" weight="1">Funeral Director</item>
    <item name="Service" weight="1">Home Appliance Repairer</item>
    <item name="Service" weight="1">Industrial Relations Analyst</item>
    <item name="Service" weight="1">Industrial Relations Specialist</item>
    <item name="Service" weight="1">Insurance Lawyer</item>
    <item name="Service" weight="1">Interpreter for the Hearing Impaired</item>
    <item name="Service" weight="1">Manicurist and Pedicurist</item>
    <item name="Service" weight="1">Parking Lot Attendant</item>
    <item name="Service" weight="1">PEntertainment Salesperson</item>
    <item name="Service" weight="1">Public Relations Specialist</item>
    <item name="Service" weight="1">Reservation Ticket Agent</item>
    <item name="Service" weight="1">Sales Promoter</item>
    <item name="Service" weight="1">Sanitary Engineer</item>
    <item name="Service" weight="1">Service Station Attendants</item>
    <item name="Service" weight="1">Skin Care Specialists</item>
    <item name="Service" weight="1">Transportation Attendants</item>
    <item name="Service" weight="1">[=Pick('Taxi Driver','Chauffeur')]</item>
    <item name="Transportation" weight="1">Air Crew Member</item>
    <item name="Transportation" weight="1">Air Crew Officer</item>
    <item name="Transportation" weight="1">Aircraft Body and Bonded Structure Repairer</item>
    <item name="Transportation" weight="1">Aircraft Cargo Handling Supervisor</item>
    <item name="Transportation" weight="1">Aircraft Examiner</item>
    <item name="Transportation" weight="1">Aircraft Launch and Recovery Officer</item>
    <item name="Transportation" weight="1">Aircraft Launch and Recovery Specialist</item>
    <item name="Transportation" weight="1">Airline Flight Control Administrator</item>
    <item name="Transportation" weight="1">Airline Flight Operations Administrator</item>
    <item name="Transportation" weight="1">Airline Flight Reservations Administrator</item>
    <item name="Transportation" weight="1">Avionics Technician</item>
    <item name="Transportation" weight="1">Commercial Diver</item>
    <item name="Transportation" weight="1">Commercial Pilot</item>
    <item name="Transportation" weight="1">Flight Engineer</item>
    <item name="Transportation" weight="1">Locomotive Engineer</item>
    <item name="Transportation" weight="1">Motor Vehicle Inspector</item>
    <item name="Transportation" weight="1">Public Transportation Inspector</item>
    <item name="Transportation" weight="1">Rail Yard Engineer</item>
    <item name="Transportation" weight="1">Railroad Engineer</item>
    <item name="Transportation" weight="1">Railroad Inspector</item>
    <item name="Transportation" weight="1">Railroad [=Pick('Conductor','Yardmaster')]</item>
    <item name="Transportation" weight="1">Ship Engineers</item>
    <item name="Transportation" weight="1">Ship Master</item>
    <item name="Transportation" weight="1">Ship Mate</item>
    <item name="Transportation" weight="1">Ship Pilot</item>
    <item name="Transportation" weight="1">Signal Switch Repairer</item>
    <item name="Transportation" weight="1">Traffic Administrator (Freight &amp; Passenger)</item>
    <item name="Transportation" weight="1">Traffic Agent</item>
    <item name="Transportation" weight="1">[=Pick('Cargo','Freight')] Agent</item>
    <item name="Volunteer" weight="1">Chaplain</item>
    <item name="Volunteer" weight="1">Clergy Member</item>
    <item name="Volunteer" weight="1">Missionary Worker</item>
    <item name="Volunteer" weight="1">Nun</item>
    <item name="Volunteer" weight="1">Pastor</item>
    <item name="Volunteer" weight="1">Peace Corps Worker</item>
  </items>
  <imports />
</generator>