<?xml version="1.0" encoding="utf-16"?>
<generator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:type="Assignment" version="2">
  <name>Colors</name>
  <supportsMaxLength>false</supportsMaxLength>
  <isLibrary>true</isLibrary>
  <items>
    <item name="COLOR" weight="0">Purple</item>
    <item name="COLOR" weight="0">Orange</item>
    <item name="COLOR" weight="0">Green</item>
  </items>
  <imports />
</generator>