<?xml version="1.0" encoding="utf-16"?>
<generator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:type="Assignment" version="2">
  <name>Psychological Disorders</name>
  <author>Lance Boudreaux</author>
  <description>Generates a psychological disorder.</description>
  <url>http://psychcentral.com/disorders/</url>
  <tags>
    <tag>Other</tag>
  </tags>
  <supportsMaxLength>false</supportsMaxLength>
  <isLibrary>false</isLibrary>
  <items>
    <item name="Start" weight="1">[Common]</item>
    <item name="Start" weight="1">[Dissociative]</item>
    <item name="Start" weight="1">[Eating]</item>
    <item name="Start" weight="1">[Paraphilic]</item>
    <item name="Start" weight="1">[SleepWake]</item>
    <item name="Start" weight="1">[Childhood]</item>
    <item name="Start" weight="1">[Personality]</item>
    <item name="Start" weight="1">[Other]</item>
    <item name="Start" weight="1">[Phobia]</item>
    <item name="Common" weight="1">Substance Abuse</item>
    <item name="Common" weight="1">Substance Dependence</item>
    <item name="Common" weight="1">Generalized Anxiety Disorder</item>
    <item name="Common" weight="1">Panic Disorder</item>
    <item name="Common" weight="1">Social Phobia</item>
    <item name="Common" weight="1">Attention Deficit Disorder</item>
    <item name="Common" weight="1">Attention Deficit Hyperactive Disorder</item>
    <item name="Common" weight="1">Bipolar Disorder</item>
    <item name="Common" weight="1">Depression</item>
    <item name="Common" weight="1">Obsessive-Compulsive Disorder</item>
    <item name="Common" weight="1">Posttraumatic Stress Disorder</item>
    <item name="Common" weight="1">Schizophrenia</item>
    <item name="Common" weight="1">Seasonal Affective Disorder</item>
    <item name="Common" weight="1">Social Anxiety</item>
    <item name="Dissociative" weight="1">Depersonalization Disorder</item>
    <item name="Dissociative" weight="1">Dissociative Amnesia</item>
    <item name="Dissociative" weight="1">Dissociative Fugue</item>
    <item name="Dissociative" weight="1">Dissociative Identity Disorder</item>
    <item name="Eating" weight="1">Anorexia Nervosa</item>
    <item name="Eating" weight="1">Binge Eating Disorder</item>
    <item name="Eating" weight="1">Bulimia Nervosa</item>
    <item name="Eating" weight="1">Pica</item>
    <item name="Paraphilic" weight="1">Dyspareunia</item>
    <item name="Paraphilic" weight="1">Erectile Disorder</item>
    <item name="Paraphilic" weight="1">Exhibitionisitc Disorder</item>
    <item name="Paraphilic" weight="1">Orgasmic Disorder</item>
    <item name="Paraphilic" weight="1">Female Sexual Arousal Disorder</item>
    <item name="Paraphilic" weight="1">Fetishistic Disorder</item>
    <item name="Paraphilic" weight="1">Frotteuristic Disorder</item>
    <item name="Paraphilic" weight="1">Hypoactive Sexual Desire Disorder</item>
    <item name="Paraphilic" weight="1">Premature Ejaculation</item>
    <item name="Paraphilic" weight="1">Sex Addiction</item>
    <item name="Paraphilic" weight="1">Sexual Masochism</item>
    <item name="Paraphilic" weight="1">Sexual Sadism</item>
    <item name="Paraphilic" weight="1">Transvestic Disorder</item>
    <item name="Paraphilic" weight="1">Vaginismus</item>
    <item name="Paraphilic" weight="1">Voyeuristic Disorder</item>
    <item name="SleepWake" weight="1">Circadian Rhythm Sleep-Wake Disorder</item>
    <item name="SleepWake" weight="1">Hypersomnolence</item>
    <item name="SleepWake" weight="1">Insomnia Disorder</item>
    <item name="SleepWake" weight="1">Nightmare Disorder</item>
    <item name="SleepWake" weight="1">Narcolepsy</item>
    <item name="SleepWake" weight="1">Rapid Eye Movement Sleep Behavior Disorder</item>
    <item name="SleepWake" weight="1">Restless Leg Syndrome</item>
    <item name="SleepWake" weight="1">Sleep Terror Disorder</item>
    <item name="SleepWake" weight="1">Sleepwalking Disorder</item>
    <item name="Childhood" weight="1">Autism Spectrum Disorder</item>
    <item name="Childhood" weight="1">Attachment Disorder</item>
    <item name="Childhood" weight="1">Autism</item>
    <item name="Childhood" weight="1">Conduct Disorder</item>
    <item name="Childhood" weight="1">Disorder of Written Expression</item>
    <item name="Childhood" weight="1">Disruptive Mood Dysregulation Disorder</item>
    <item name="Childhood" weight="1">Encopresis</item>
    <item name="Childhood" weight="1">Enuresis</item>
    <item name="Childhood" weight="1">Expressive Language Disorder</item>
    <item name="Childhood" weight="1">Mathematics Disorder</item>
    <item name="Childhood" weight="1">Intellectual Disability</item>
    <item name="Childhood" weight="1">Oppositional Defiant Disorder</item>
    <item name="Childhood" weight="1">Reading Disorder</item>
    <item name="Childhood" weight="1">Rumination Disorder</item>
    <item name="Childhood" weight="1">Selective Mutism</item>
    <item name="Childhood" weight="1">Seperation Anxiety Disorder</item>
    <item name="Childhood" weight="1">Social Communication Disorder</item>
    <item name="Childhood" weight="1">Stereotypic Movement Disorder</item>
    <item name="Childhood" weight="1">Stuttering</item>
    <item name="Childhood" weight="1">Tourette's Disorder</item>
    <item name="Childhood" weight="1">Transient Tic Disorder</item>
    <item name="Personality" weight="1">Antisocial Personality Disorder</item>
    <item name="Personality" weight="1">Avoidant Personality Disorder</item>
    <item name="Personality" weight="1">Borderline Personality Disorder</item>
    <item name="Personality" weight="1">Dependent Personality Disorder</item>
    <item name="Personality" weight="1">Histrionic Personality Disorder</item>
    <item name="Personality" weight="1">Dissociative Identity Disorder</item>
    <item name="Personality" weight="1">Narcissistic Personality Disorder</item>
    <item name="Personality" weight="1">Obssessive Compulsive Personality Disorder</item>
    <item name="Personality" weight="1">Paranoid Personality Disorder</item>
    <item name="Personality" weight="1">Schizoid Personality Disorder</item>
    <item name="Personality" weight="1">Schitotypal Personality Disorder</item>
    <item name="Other" weight="1">Acute Stress Disorder</item>
    <item name="Other" weight="1">Adjustment Disorder</item>
    <item name="Other" weight="1">Alzheimer's Disease</item>
    <item name="Other" weight="1">Bereavement</item>
    <item name="Other" weight="1">Body Dysmorphic Disorder</item>
    <item name="Other" weight="1">Brief Psychotic Disorder</item>
    <item name="Other" weight="1">Conversion Disorder</item>
    <item name="Other" weight="1">Cyclothymic Disorder</item>
    <item name="Other" weight="1">Delusional Disorder</item>
    <item name="Other" weight="1">Disinhibited Social Engagement Disorder</item>
    <item name="Other" weight="1">Dysthymic Disorder</item>
    <item name="Other" weight="1">Gender Dysphoria</item>
    <item name="Other" weight="1">Hoarding Disorder</item>
    <item name="Other" weight="1">Hypochondriasis</item>
    <item name="Other" weight="1">Intermittent Explosive Disorder</item>
    <item name="Other" weight="1">Kleptomania</item>
    <item name="Other" weight="1">Major Neurocognitive Disorder</item>
    <item name="Other" weight="1">Minor Neurocognitive Disorder</item>
    <item name="Other" weight="1">Necrophilia</item>
    <item name="Other" weight="1">Pain Disorder</item>
    <item name="Other" weight="1">Panic Attack</item>
    <item name="Other" weight="1">Pathological Gambling</item>
    <item name="Other" weight="1">Pedophilia</item>
    <item name="Other" weight="1">Premenstrual Dysphoric Disorder</item>
    <item name="Other" weight="1">Unspecified Psychotic Disorder</item>
    <item name="Other" weight="1">Pyromania</item>
    <item name="Other" weight="1">Reactive Attachment Disorder</item>
    <item name="Other" weight="1">Schizoaffective Disorder</item>
    <item name="Other" weight="1">Schizophreniform Disorder</item>
    <item name="Other" weight="1">Shared Psychotic Disorder</item>
    <item name="Other" weight="1">Somatic Symptom Disorder</item>
    <item name="Other" weight="1">Trichotillomania</item>
    <item name="Phobia" weight="1">Ablutophobia :  Fear of washing or bathing.</item>
    <item name="Phobia" weight="1">Acarophobia :  Fear of itching or of the insects that cause itching.</item>
    <item name="Phobia" weight="1">Acerophobia :  Fear of sourness.</item>
    <item name="Phobia" weight="1">Achluophobia :  Fear of darkness.</item>
    <item name="Phobia" weight="1">Acousticophobia :  Fear of noise.</item>
    <item name="Phobia" weight="1">Acrophobia :  Fear of heights.</item>
    <item name="Phobia" weight="1">Aerophobia :  Fear of drafts, air swallowing, or airborne noxious substances.</item>
    <item name="Phobia" weight="1">Aeroacrophobia :  Fear of open high places.</item>
    <item name="Phobia" weight="1">Aeronausiphobia :  Fear of vomiting secondary to airsickness.</item>
    <item name="Phobia" weight="1">Agateophobia :  Fear of insanity.</item>
    <item name="Phobia" weight="1">Agliophobia :  Fear of pain.</item>
    <item name="Phobia" weight="1">Agoraphobia :  Fear of open spaces or of being in crowded, public places like markets. Fear of leaving a safe place.</item>
    <item name="Phobia" weight="1">Agraphobia :  Fear of sexual abuse.</item>
    <item name="Phobia" weight="1">Agrizoophobia :  Fear of wild animals.</item>
    <item name="Phobia" weight="1">Agyrophobia :  Fear of streets or crossing the street.</item>
    <item name="Phobia" weight="1">Aichmophobia :  Fear of needles or pointed objects.</item>
    <item name="Phobia" weight="1">Ailurophobia :  Fear of cats.</item>
    <item name="Phobia" weight="1">Albuminurophobia :  Fear of kidney disease.</item>
    <item name="Phobia" weight="1">Alektorophobia :  Fear of chickens.</item>
    <item name="Phobia" weight="1">Algophobia :  Fear of pain.</item>
    <item name="Phobia" weight="1">Alliumphobia :  Fear of garlic.</item>
    <item name="Phobia" weight="1">Allodoxaphobia :  Fear of opinions.</item>
    <item name="Phobia" weight="1">Altophobia :  Fear of heights.</item>
    <item name="Phobia" weight="1">Amathophobia :  Fear of dust.</item>
    <item name="Phobia" weight="1">Amaxophobia :  Fear of riding in a car.</item>
    <item name="Phobia" weight="1">Ambulophobia :  Fear of walking.</item>
    <item name="Phobia" weight="1">Amnesiphobia :  Fear of amnesia.</item>
    <item name="Phobia" weight="1">Amychophobia :  Fear of scratches or being scratched.</item>
    <item name="Phobia" weight="1">Anablephobia :  Fear of looking up.</item>
    <item name="Phobia" weight="1">Ancraophobia :  Fear of wind. </item>
    <item name="Phobia" weight="1">Androphobia :  Fear of men.</item>
    <item name="Phobia" weight="1">Anemophobia :  Fear of air drafts or wind.</item>
    <item name="Phobia" weight="1">Anginophobia :  Fear of angina, choking or narrowness.</item>
    <item name="Phobia" weight="1">Anglophobia :  Fear of England or English culture, etc.</item>
    <item name="Phobia" weight="1">Angrophobia  :  Fear of anger or of becoming angry.</item>
    <item name="Phobia" weight="1">Ankylophobia :  Fear of immobility of a joint.</item>
    <item name="Phobia" weight="1">Anthrophobia :  Fear of flowers.</item>
    <item name="Phobia" weight="1">Anthropophobia :  Fear of people or society.</item>
    <item name="Phobia" weight="1">Antlophobia :  Fear of floods.</item>
    <item name="Phobia" weight="1">Anuptaphobia :  Fear of staying single.</item>
    <item name="Phobia" weight="1">Apeirophobia :  Fear of infinity.</item>
    <item name="Phobia" weight="1">Aphenphosmphobia :  Fear of being touched. </item>
    <item name="Phobia" weight="1">Apiphobia :  Fear of bees.</item>
    <item name="Phobia" weight="1">Apotemnophobia :  Fear of persons with amputations.</item>
    <item name="Phobia" weight="1">Arachibutyrophobia :  Fear of peanut butter sticking to the roof of the mouth.</item>
    <item name="Phobia" weight="1">Arachnephobia or Arachnophobia :  Fear of spiders.</item>
    <item name="Phobia" weight="1">Arithmophobia :  Fear of numbers.</item>
    <item name="Phobia" weight="1">Arrhenphobia :  Fear of men.</item>
    <item name="Phobia" weight="1">Arsonphobia :  Fear of fire.</item>
    <item name="Phobia" weight="1">Asthenophobia :  Fear of fainting or weakness.</item>
    <item name="Phobia" weight="1">Astraphobia :  Fear of thunder and lightning.</item>
    <item name="Phobia" weight="1">Astrophobia :  Fear of stars or celestial space.</item>
    <item name="Phobia" weight="1">Asymmetriphobia :  Fear of asymmetrical things.</item>
    <item name="Phobia" weight="1">Ataxiophobia :  Fear of ataxia. (muscular in-coordination)</item>
    <item name="Phobia" weight="1">Ataxophobia :  Fear of disorder or untidiness.</item>
    <item name="Phobia" weight="1">Atelophobia :  Fear of imperfection.</item>
    <item name="Phobia" weight="1">Atephobia :  Fear of ruin or ruins.</item>
    <item name="Phobia" weight="1">Athazagoraphobia :  Fear of being forgotten, ignored, or forgetting.</item>
    <item name="Phobia" weight="1">Atomosophobia :  Fear of atomic explosions.</item>
    <item name="Phobia" weight="1">Atychiphobia :  Fear of failure.</item>
    <item name="Phobia" weight="1">Aulophobia :  Fear of flutes.</item>
    <item name="Phobia" weight="1">Aurophobia :  Fear of gold.</item>
    <item name="Phobia" weight="1">Auroraphobia :  Fear of Northern lights.</item>
    <item name="Phobia" weight="1">Autodysomophobia :  Fear of one that has a vile odor.</item>
    <item name="Phobia" weight="1">Automatonophobia :  Fear of ventriloquist's dummies, animatronic creatures, wax statues (anything that falsely represents a sentient being).</item>
    <item name="Phobia" weight="1">Automysophobia :  Fear of being dirty.</item>
    <item name="Phobia" weight="1">Autophobia :  Fear of being alone or of oneself.</item>
    <item name="Phobia" weight="1">Aviophobia  :  Fear of flying.</item>
    <item name="Phobia" weight="1">Bacillophobia :  Fear of microbes.</item>
    <item name="Phobia" weight="1">Bacteriophobia :  Fear of bacteria.</item>
    <item name="Phobia" weight="1">Ballistophobia :  Fear of missiles or bullets.</item>
    <item name="Phobia" weight="1">Bolshephobia :  Fear of Bolsheviks.</item>
    <item name="Phobia" weight="1">Barophobia :  Fear of gravity.</item>
    <item name="Phobia" weight="1">Basophobia :  Inability to stand. Fear of walking or falling.</item>
    <item name="Phobia" weight="1">Bathmophobia :  Fear of stairs or steep slopes.</item>
    <item name="Phobia" weight="1">Bathophobia :  Fear of depth.</item>
    <item name="Phobia" weight="1">Batophobia :  Fear of heights or being close to high buildings.</item>
    <item name="Phobia" weight="1">Batrachophobia :  Fear of amphibians, such as frogs, newts, salamanders, etc.</item>
    <item name="Phobia" weight="1">Belonephobia :  Fear of pins and needles.</item>
    <item name="Phobia" weight="1">Bibliophobia :  Fear of books.</item>
    <item name="Phobia" weight="1">Blennophobia :  Fear of slime.</item>
    <item name="Phobia" weight="1">Bogyphobia :  Fear of bogeys or the bogeyman.</item>
    <item name="Phobia" weight="1">Botanophobia :  Fear of plants.</item>
    <item name="Phobia" weight="1">Bromidrosiphobia :  Fear of body smells.</item>
    <item name="Phobia" weight="1">Brontophobia :  Fear of thunder and lightning.</item>
    <item name="Phobia" weight="1">Bufonophobia :  Fear of toads.</item>
    <item name="Phobia" weight="1">Cacophobia :  Fear of ugliness.</item>
    <item name="Phobia" weight="1">Cainophobia :  Fear of newness, novelty.</item>
    <item name="Phobia" weight="1">Caligynephobia :  Fear of beautiful women.</item>
    <item name="Phobia" weight="1">Cancerophobia :  Fear of cancer.</item>
    <item name="Phobia" weight="1">Cardiophobia :  Fear of the heart.</item>
    <item name="Phobia" weight="1">Carnophobia :  Fear of meat.</item>
    <item name="Phobia" weight="1">Catagelophobia :  Fear of being ridiculed.</item>
    <item name="Phobia" weight="1">Catapedaphobia :  Fear of jumping from high and low places.</item>
    <item name="Phobia" weight="1">Cathisophobia :  Fear of sitting.</item>
    <item name="Phobia" weight="1">Catoptrophobia :  Fear of mirrors.</item>
    <item name="Phobia" weight="1">Cenophobia :  Fear of new things or ideas.</item>
    <item name="Phobia" weight="1">Ceraunophobia:  Fear of thunder and lightning.</item>
    <item name="Phobia" weight="1">Chaetophobia :  Fear of hair.</item>
    <item name="Phobia" weight="1">Cheimaphobia :  Fear of cold.</item>
    <item name="Phobia" weight="1">Chemophobia :  Fear of chemicals or working with chemicals.</item>
    <item name="Phobia" weight="1">Cherophobia :  Fear of gaiety.</item>
    <item name="Phobia" weight="1">Chionophobia :  Fear of snow.</item>
    <item name="Phobia" weight="1">Chiraptophobia :  Fear of being touched.</item>
    <item name="Phobia" weight="1">Chirophobia :  Fear of hands.</item>
    <item name="Phobia" weight="1">Chiroptophobia :  Fear of bats.</item>
    <item name="Phobia" weight="1">Cholerophobia :  Fear of anger or the fear of cholera.</item>
    <item name="Phobia" weight="1">Chorophobia :  Fear of dancing.</item>
    <item name="Phobia" weight="1">Chrometophobia :  Fear of money.</item>
    <item name="Phobia" weight="1">Chromophobia :  Fear of colors.</item>
    <item name="Phobia" weight="1">Chronophobia :  Fear of time.</item>
    <item name="Phobia" weight="1">Chronomentrophobia :  Fear of clocks.</item>
    <item name="Phobia" weight="1">Cibophobia :  Fear of food.</item>
    <item name="Phobia" weight="1">Claustrophobia :  Fear of confined spaces.</item>
    <item name="Phobia" weight="1">Cleithrophobia :  Fear of being locked in an enclosed place.</item>
    <item name="Phobia" weight="1">Cleptophobia :  Fear of stealing.</item>
    <item name="Phobia" weight="1">Climacophobia :  Fear of stairs, climbing, or of falling downstairs.</item>
    <item name="Phobia" weight="1">Clinophobia :  Fear of going to bed.</item>
    <item name="Phobia" weight="1">Clithrophobia :  Fear of being enclosed.</item>
    <item name="Phobia" weight="1">Cnidophobia :  Fear of stings.</item>
    <item name="Phobia" weight="1">Cometophobia :  Fear of comets.</item>
    <item name="Phobia" weight="1">Coimetrophobia :  Fear of cemeteries.</item>
    <item name="Phobia" weight="1">Coitophobia :  Fear of coitus.</item>
    <item name="Phobia" weight="1">Contreltophobia :  Fear of sexual abuse.</item>
    <item name="Phobia" weight="1">Coprastasophobia :  Fear of constipation.</item>
    <item name="Phobia" weight="1">Coprophobia :  Fear of feces.</item>
    <item name="Phobia" weight="1">Consecotaleophobia :  Fear of chopsticks.</item>
    <item name="Phobia" weight="1">Coulrophobia :  Fear of clowns.</item>
    <item name="Phobia" weight="1">Counterphobia :  The preference by a phobic for fearful situations.</item>
    <item name="Phobia" weight="1">Cremnophobia :  Fear of precipices.</item>
    <item name="Phobia" weight="1">Cryophobia :  Fear of extreme cold, ice or frost.</item>
    <item name="Phobia" weight="1">Crystallophobia :  Fear of crystals or glass.</item>
    <item name="Phobia" weight="1">Cyberphobia :  Fear of computers or working on a computer.</item>
    <item name="Phobia" weight="1">Cyclophobia :  Fear of bicycles.</item>
    <item name="Phobia" weight="1">Cymophobia  :  Fear of waves or wave like motions.</item>
    <item name="Phobia" weight="1">Cynophobia :  Fear of dogs or rabies.</item>
    <item name="Phobia" weight="1">Cypridophobia  :  Fear of prostitutes or venereal disease.</item>
    <item name="Phobia" weight="1">Decidophobia :  Fear of making decisions.</item>
    <item name="Phobia" weight="1">Defecaloesiophobia :  Fear of painful bowels movements.</item>
    <item name="Phobia" weight="1">Deipnophobia :  Fear of dining or dinner conversations.</item>
    <item name="Phobia" weight="1">Dementophobia :  Fear of insanity.</item>
    <item name="Phobia" weight="1">Demonophobia :  Fear of demons.</item>
    <item name="Phobia" weight="1">Demophobia :  Fear of crowds. (Agoraphobia)</item>
    <item name="Phobia" weight="1">Dendrophobia :  Fear of trees.</item>
    <item name="Phobia" weight="1">Dentophobia :  Fear of dentists.</item>
    <item name="Phobia" weight="1">Dermatophobia :  Fear of skin lesions.</item>
    <item name="Phobia" weight="1">Dermatosiophobia :  Fear of skin disease.</item>
    <item name="Phobia" weight="1">Dextrophobia :  Fear of objects at the right side of the body.</item>
    <item name="Phobia" weight="1">Diabetophobia :  Fear of diabetes.</item>
    <item name="Phobia" weight="1">Didaskaleinophobia :  Fear of going to school.</item>
    <item name="Phobia" weight="1">Dikephobia :  Fear of justice.</item>
    <item name="Phobia" weight="1">Dinophobia :  Fear of dizziness or whirlpools.</item>
    <item name="Phobia" weight="1">Diplophobia :  Fear of double vision.</item>
    <item name="Phobia" weight="1">Dipsophobia :  Fear of drinking.</item>
    <item name="Phobia" weight="1">Dishabiliophobia :  Fear of undressing in front of someone.</item>
    <item name="Phobia" weight="1">Disposophobia :  Fear of throwing stuff out. Hoarding.</item>
    <item name="Phobia" weight="1">Domatophobia :  Fear of houses or being in a house.</item>
    <item name="Phobia" weight="1">Doraphobia :  Fear of fur or skins of animals.</item>
    <item name="Phobia" weight="1">Doxophobia :  Fear of expressing opinions or of receiving praise.</item>
    <item name="Phobia" weight="1">Dromophobia :  Fear of crossing streets.</item>
    <item name="Phobia" weight="1">Dutchphobia :  Fear of the Dutch.</item>
    <item name="Phobia" weight="1">Dysmorphophobia :  Fear of deformity.</item>
    <item name="Phobia" weight="1">Dystychiphobia :  Fear of accidents.</item>
    <item name="Phobia" weight="1">Ecclesiophobia :  Fear of church.</item>
    <item name="Phobia" weight="1">Ecophobia :  Fear of home.</item>
    <item name="Phobia" weight="1">Eicophobia :  Fear of home surroundings.</item>
    <item name="Phobia" weight="1">Eisoptrophobia :  Fear of mirrors or of seeing oneself in a mirror.</item>
    <item name="Phobia" weight="1">Electrophobia :  Fear of electricity.</item>
    <item name="Phobia" weight="1">Eleutherophobia :  Fear of freedom.</item>
    <item name="Phobia" weight="1">Elurophobia :  Fear of cats. </item>
    <item name="Phobia" weight="1">Emetophobia :  Fear of vomiting.</item>
    <item name="Phobia" weight="1">Enetophobia :  Fear of pins.</item>
    <item name="Phobia" weight="1">Enochlophobia :  Fear of crowds.</item>
    <item name="Phobia" weight="1">Enosiophobia :  Fear of having committed an unpardonable sin or of criticism.</item>
    <item name="Phobia" weight="1">Entomophobia :  Fear of insects.</item>
    <item name="Phobia" weight="1">Eosophobia :  Fear of dawn or daylight.</item>
    <item name="Phobia" weight="1">Ephebiphobia :  Fear of teenagers.</item>
    <item name="Phobia" weight="1">Epistaxiophobia :  Fear of nosebleeds.</item>
    <item name="Phobia" weight="1">Epistemophobia :  Fear of knowledge.</item>
    <item name="Phobia" weight="1">Equinophobia :  Fear of horses.</item>
    <item name="Phobia" weight="1">Eremophobia :  Fear of being oneself or of loneliness.</item>
    <item name="Phobia" weight="1">Ereuthrophobia :  Fear of blushing.</item>
    <item name="Phobia" weight="1">Ergasiophobia :  Fear of work or functioning or surgeon's fear of operating.</item>
    <item name="Phobia" weight="1">Ergophobia :  Fear of work.</item>
    <item name="Phobia" weight="1">Erotophobia :  Fear of sexual love or sexual questions.</item>
    <item name="Phobia" weight="1">Euphobia :  Fear of hearing good news.</item>
    <item name="Phobia" weight="1">Eurotophobia :  Fear of female genitalia.</item>
    <item name="Phobia" weight="1">Erythrophobia :  Fear of redlights, blushing or Red.</item>
    <item name="Phobia" weight="1">Febriphobia :  Fear of fever.</item>
    <item name="Phobia" weight="1">Felinophobia :  Fear of cats.</item>
    <item name="Phobia" weight="1">Francophobia :  Fear of France or French culture.</item>
    <item name="Phobia" weight="1">Frigophobia :  Fear of cold or cold things.</item>
    <item name="Phobia" weight="1">Galeophobia :  Fear of cats.</item>
    <item name="Phobia" weight="1">Gallophobia :  Fear France or French culture.</item>
    <item name="Phobia" weight="1">Gamophobia :  Fear of marriage.</item>
    <item name="Phobia" weight="1">Geliophobia :  Fear of laughter.</item>
    <item name="Phobia" weight="1">Gelotophobia :  Fear of being laughed at.</item>
    <item name="Phobia" weight="1">Geniophobia :  Fear of chins.</item>
    <item name="Phobia" weight="1">Genophobia :  Fear of sex.</item>
    <item name="Phobia" weight="1">Genuphobia :  Fear of knees.</item>
    <item name="Phobia" weight="1">Gephyrophobia :  Fear of crossing bridges.</item>
    <item name="Phobia" weight="1">Germanophobia :  Fear of Germany or German culture.</item>
    <item name="Phobia" weight="1">Gerascophobia :  Fear of growing old.</item>
    <item name="Phobia" weight="1">Gerontophobia :  Fear of old people or of growing old.</item>
    <item name="Phobia" weight="1">Geumaphobia :  Fear of taste.</item>
    <item name="Phobia" weight="1">Glossophobia :  Fear of speaking in public or of trying to speak.</item>
    <item name="Phobia" weight="1">Gnosiophobia :  Fear of knowledge.</item>
    <item name="Phobia" weight="1">Graphophobia :  Fear of writing or handwriting.</item>
    <item name="Phobia" weight="1">Gymnophobia :  Fear of nudity.</item>
    <item name="Phobia" weight="1">Gynephobia :  Fear of women.</item>
    <item name="Phobia" weight="1">Hadephobia :  Fear of hell.</item>
    <item name="Phobia" weight="1">Hagiophobia :  Fear of saints or holy things.</item>
    <item name="Phobia" weight="1">Hamartophobia :  Fear of sinning.</item>
    <item name="Phobia" weight="1">Haphephobia :  Fear of being touched.</item>
    <item name="Phobia" weight="1">Harpaxophobia :  Fear of being robbed.</item>
    <item name="Phobia" weight="1">Hedonophobia :  Fear of feeling pleasure.</item>
    <item name="Phobia" weight="1">Heliophobia :  Fear of the sun.</item>
    <item name="Phobia" weight="1">Hellenologophobia :  Fear of Greek terms or complex scientific terminology.</item>
    <item name="Phobia" weight="1">Helminthophobia :  Fear of being infested with worms.</item>
    <item name="Phobia" weight="1">Hemophobia :  Fear of blood.</item>
    <item name="Phobia" weight="1">Heresyphobia :  Fear of challenges to official doctrine or of radical deviation.</item>
    <item name="Phobia" weight="1">Herpetophobia :  Fear of reptiles or creepy, crawly things.</item>
    <item name="Phobia" weight="1">Heterophobia :  Fear of the opposite sex. </item>
    <item name="Phobia" weight="1">Hexakosioihexekontahexaphobia :  Fear of the number 666.</item>
    <item name="Phobia" weight="1">Hierophobia :  Fear of priests or sacred things.</item>
    <item name="Phobia" weight="1">Hippophobia :  Fear of horses.</item>
    <item name="Phobia" weight="1">Hippopotomonstrosesquipedaliophobia :  Fear of long words.</item>
    <item name="Phobia" weight="1">Hobophobia :  Fear of bums or beggars.</item>
    <item name="Phobia" weight="1">Hodophobia :  Fear of road travel.</item>
    <item name="Phobia" weight="1">Hormephobia :  Fear of shock.</item>
    <item name="Phobia" weight="1">Homichlophobia :  Fear of fog.</item>
    <item name="Phobia" weight="1">Homilophobia :  Fear of sermons.</item>
    <item name="Phobia" weight="1">Hominophobia :  Fear of men.</item>
    <item name="Phobia" weight="1">Homophobia :  Fear of sameness, monotony or of homosexuality or of becoming homosexual.</item>
    <item name="Phobia" weight="1">Hoplophobia :  Fear of firearms.</item>
    <item name="Phobia" weight="1">Hydrargyophobia :  Fear of mercurial medicines.</item>
    <item name="Phobia" weight="1">Hydrophobia :  Fear of water or of rabies.</item>
    <item name="Phobia" weight="1">Hydrophobophobia :  Fear of rabies.</item>
    <item name="Phobia" weight="1">Hyelophobia :  Fear of glass.</item>
    <item name="Phobia" weight="1">Hygrophobia :  Fear of liquids, dampness, or moisture.</item>
    <item name="Phobia" weight="1">Hylephobia :  Fear of materialism or the fear of epilepsy.</item>
    <item name="Phobia" weight="1">Hylophobia :  Fear of forests.</item>
    <item name="Phobia" weight="1">Hypengyophobia  :  Fear of responsibility.</item>
    <item name="Phobia" weight="1">Hypnophobia :  Fear of sleep or of being hypnotized.</item>
    <item name="Phobia" weight="1">Hypsiphobia :  Fear of height.</item>
    <item name="Phobia" weight="1">Iatrophobia :  Fear of going to the doctor or of doctors.</item>
    <item name="Phobia" weight="1">Ichthyophobia :  Fear of fish.</item>
    <item name="Phobia" weight="1">Ideophobia :  Fear of ideas.</item>
    <item name="Phobia" weight="1">Illyngophobia :  Fear of vertigo or feeling dizzy when looking down.</item>
    <item name="Phobia" weight="1">Iophobia :  Fear of poison.</item>
    <item name="Phobia" weight="1">Insectophobia  :  Fear of insects.</item>
    <item name="Phobia" weight="1">Isolophobia :  Fear of solitude, being alone.</item>
    <item name="Phobia" weight="1">Isopterophobia :  Fear of termites, insects that eat wood.</item>
    <item name="Phobia" weight="1">Ithyphallophobia :  Fear of seeing, thinking about or having an erect penis.</item>
    <item name="Phobia" weight="1">Japanophobia :  Fear of Japanese.</item>
    <item name="Phobia" weight="1">Judeophobia :  Fear of Jews.</item>
    <item name="Phobia" weight="1">Kainolophobia  :  Fear of anything new, novelty.</item>
    <item name="Phobia" weight="1">Kakorrhaphiophobia :  Fear of failure or defeat.</item>
    <item name="Phobia" weight="1">Katagelophobia :  Fear of ridicule.</item>
    <item name="Phobia" weight="1">Kathisophobia :  Fear of sitting down.</item>
    <item name="Phobia" weight="1">Katsaridaphobia :  Fear of cockroaches.</item>
    <item name="Phobia" weight="1">Kenophobia :  Fear of voids or empty spaces.</item>
    <item name="Phobia" weight="1">Keraunophobia  :  Fear of thunder and lightning.</item>
    <item name="Phobia" weight="1">Kinetophobia  :  Fear of movement or motion.</item>
    <item name="Phobia" weight="1">Kleptophobia :  Fear of stealing.</item>
    <item name="Phobia" weight="1">Koinoniphobia :  Fear of rooms.</item>
    <item name="Phobia" weight="1">Kolpophobia :  Fear of genitals, particularly female.</item>
    <item name="Phobia" weight="1">Kopophobia :  Fear of fatigue.</item>
    <item name="Phobia" weight="1">Koniophobia :  Fear of dust. </item>
    <item name="Phobia" weight="1">Kosmikophobia :  Fear of cosmic phenomenon.</item>
    <item name="Phobia" weight="1">Kymophobia :  Fear of waves. </item>
    <item name="Phobia" weight="1">Kynophobia :  Fear of rabies.</item>
    <item name="Phobia" weight="1">Kyphophobia :  Fear of stooping.</item>
    <item name="Phobia" weight="1">Lachanophobia :  Fear of vegetables.</item>
    <item name="Phobia" weight="1">Laliophobia :  Fear of speaking.</item>
    <item name="Phobia" weight="1">Leprophobia :  Fear of leprosy.</item>
    <item name="Phobia" weight="1">Leukophobia :  Fear of the color white.</item>
    <item name="Phobia" weight="1">Levophobia :  Fear of things to the left side of the body.</item>
    <item name="Phobia" weight="1">Ligyrophobia :  Fear of loud noises.</item>
    <item name="Phobia" weight="1">Lilapsophobia :  Fear of tornadoes and hurricanes.</item>
    <item name="Phobia" weight="1">Limnophobia :  Fear of lakes.</item>
    <item name="Phobia" weight="1">Linonophobia :  Fear of string.</item>
    <item name="Phobia" weight="1">Liticaphobia :  Fear of lawsuits.</item>
    <item name="Phobia" weight="1">Lockiophobia :  Fear of childbirth.</item>
    <item name="Phobia" weight="1">Logizomechanophobia :  Fear of computers.</item>
    <item name="Phobia" weight="1">Logophobia :  Fear of words.</item>
    <item name="Phobia" weight="1">Lutraphobia :  Fear of otters.</item>
    <item name="Phobia" weight="1">Lygophobia :  Fear of darkness.</item>
    <item name="Phobia" weight="1">Lyssophobia :  Fear of rabies or of becoming mad.</item>
    <item name="Phobia" weight="1">Macrophobia :  Fear of long waits.</item>
    <item name="Phobia" weight="1">Mageirocophobia :  Fear of cooking.</item>
    <item name="Phobia" weight="1">Maieusiophobia :  Fear of childbirth.</item>
    <item name="Phobia" weight="1">Malaxophobia :  Fear of love play.</item>
    <item name="Phobia" weight="1">Maniaphobia :  Fear of insanity.</item>
    <item name="Phobia" weight="1">Mastigophobia :  Fear of punishment.</item>
    <item name="Phobia" weight="1">Mechanophobia :  Fear of machines.</item>
    <item name="Phobia" weight="1">Medomalacuphobia :  Fear of losing an erection.</item>
    <item name="Phobia" weight="1">Medorthophobia :  Fear of an erect penis.</item>
    <item name="Phobia" weight="1">Megalophobia :  Fear of large things.</item>
    <item name="Phobia" weight="1">Melissophobia :  Fear of bees.</item>
    <item name="Phobia" weight="1">Melanophobia :  Fear of the color black.</item>
    <item name="Phobia" weight="1">Melophobia :  Fear or hatred of music.</item>
    <item name="Phobia" weight="1">Meningitophobia :  Fear of brain disease.</item>
    <item name="Phobia" weight="1">Menophobia :  Fear of menstruation.</item>
    <item name="Phobia" weight="1">Merinthophobia :  Fear of being bound or tied up.</item>
    <item name="Phobia" weight="1">Metallophobia :  Fear of metal.</item>
    <item name="Phobia" weight="1">Metathesiophobia :  Fear of changes.</item>
    <item name="Phobia" weight="1">Meteorophobia :  Fear of meteors.</item>
    <item name="Phobia" weight="1">Methyphobia :  Fear of alcohol.</item>
    <item name="Phobia" weight="1">Metrophobia :  Fear or hatred of poetry.</item>
    <item name="Phobia" weight="1">Microbiophobia :  Fear of microbes. </item>
    <item name="Phobia" weight="1">Microphobia :  Fear of small things.</item>
    <item name="Phobia" weight="1">Misophobia :  Fear of being contaminated with dirt or germs.</item>
    <item name="Phobia" weight="1">Mnemophobia :  Fear of memories.</item>
    <item name="Phobia" weight="1">Molysmophobia :  Fear of dirt or contamination.</item>
    <item name="Phobia" weight="1">Monophobia :  Fear of solitude or being alone.</item>
    <item name="Phobia" weight="1">Monopathophobia :  Fear of definite disease.</item>
    <item name="Phobia" weight="1">Motorphobia :  Fear of automobiles.</item>
    <item name="Phobia" weight="1">Mottephobia :  Fear of moths.</item>
    <item name="Phobia" weight="1">Musophobia :  Fear of mice.</item>
    <item name="Phobia" weight="1">Mycophobia :  Fear or aversion to mushrooms.</item>
    <item name="Phobia" weight="1">Mycrophobia :  Fear of small things.</item>
    <item name="Phobia" weight="1">Myctophobia :  Fear of darkness.</item>
    <item name="Phobia" weight="1">Myrmecophobia :  Fear of ants.</item>
    <item name="Phobia" weight="1">Mythophobia :  Fear of myths or stories or false statements.</item>
    <item name="Phobia" weight="1">Myxophobia :  Fear of slime.</item>
    <item name="Phobia" weight="1">Nebulaphobia :  Fear of fog. </item>
    <item name="Phobia" weight="1">Necrophobia :  Fear of death or dead things.</item>
    <item name="Phobia" weight="1">Nelophobia :  Fear of glass.</item>
    <item name="Phobia" weight="1">Neopharmaphobia :  Fear of new drugs.</item>
    <item name="Phobia" weight="1">Neophobia :  Fear of anything new.</item>
    <item name="Phobia" weight="1">Nephophobia :  Fear of clouds.</item>
    <item name="Phobia" weight="1">Noctiphobia :  Fear of the night.</item>
    <item name="Phobia" weight="1">Nomatophobia :  Fear of names.</item>
    <item name="Phobia" weight="1">Nosocomephobia :  Fear of hospitals.</item>
    <item name="Phobia" weight="1">Nosophobia :  Fear of becoming ill.</item>
    <item name="Phobia" weight="1">Nostophobia :  Fear of returning home.</item>
    <item name="Phobia" weight="1">Novercaphobia :  Fear of your step : mother.</item>
    <item name="Phobia" weight="1">Nucleomituphobia :  Fear of nuclear weapons.</item>
    <item name="Phobia" weight="1">Nudophobia :  Fear of nudity.</item>
    <item name="Phobia" weight="1">Numerophobia :  Fear of numbers.</item>
    <item name="Phobia" weight="1">Nyctohylophobia :  Fear of dark wooded areas or of forests at night</item>
    <item name="Phobia" weight="1">Nyctophobia :  Fear of the dark or of night.</item>
    <item name="Phobia" weight="1">Obesophobia :  Fear of gaining weight.</item>
    <item name="Phobia" weight="1">Ochlophobia :  Fear of crowds or mobs.</item>
    <item name="Phobia" weight="1">Ochophobia :  Fear of vehicles.</item>
    <item name="Phobia" weight="1">Octophobia  :  Fear of the figure 8.</item>
    <item name="Phobia" weight="1">Odontophobia :  Fear of teeth or dental surgery.</item>
    <item name="Phobia" weight="1">Odynophobia :  Fear of pain.</item>
    <item name="Phobia" weight="1">Oenophobia :  Fear of wines.</item>
    <item name="Phobia" weight="1">Oikophobia :  Fear of home surroundings, house.</item>
    <item name="Phobia" weight="1">Olfactophobia :  Fear of smells.</item>
    <item name="Phobia" weight="1">Ombrophobia :  Fear of rain or of being rained on.</item>
    <item name="Phobia" weight="1">Ommetaphobia :  Fear of eyes.</item>
    <item name="Phobia" weight="1">Omphalophobia :  Fear of belly buttons.</item>
    <item name="Phobia" weight="1">Oneirophobia :  Fear of dreams.</item>
    <item name="Phobia" weight="1">Oneirogmophobia :  Fear of wet dreams.</item>
    <item name="Phobia" weight="1">Onomatophobia :  Fear of hearing a certain word or of names.</item>
    <item name="Phobia" weight="1">Ophidiophobia :  Fear of snakes. </item>
    <item name="Phobia" weight="1">Ophthalmophobia :  Fear of being stared at.</item>
    <item name="Phobia" weight="1">Opiophobia :  Fear medical doctors experience of prescribing needed pain medications for patients.</item>
    <item name="Phobia" weight="1">Optophobia :  Fear of opening one's eyes.</item>
    <item name="Phobia" weight="1">Ornithophobia :  Fear of birds.</item>
    <item name="Phobia" weight="1">Orthophobia :  Fear of property.</item>
    <item name="Phobia" weight="1">Osmophobia :  Fear of smells or odors.</item>
    <item name="Phobia" weight="1">Ostraconophobia :  Fear of shellfish.</item>
    <item name="Phobia" weight="1">Ouranophobia :  Fear of heaven.</item>
    <item name="Phobia" weight="1">Pagophobia :  Fear of ice or frost.</item>
    <item name="Phobia" weight="1">Panthophobia :  Fear of suffering and disease.</item>
    <item name="Phobia" weight="1">Panophobia :  Fear of everything.</item>
    <item name="Phobia" weight="1">Papaphobia :  Fear of the Pope.</item>
    <item name="Phobia" weight="1">Papyrophobia :  Fear of paper.</item>
    <item name="Phobia" weight="1">Paralipophobia :  Fear of neglecting duty or responsibility.</item>
    <item name="Phobia" weight="1">Paraphobia :  Fear of sexual perversion.</item>
    <item name="Phobia" weight="1">Parasitophobia :  Fear of parasites.</item>
    <item name="Phobia" weight="1">Paraskavedekatriaphobia :  Fear of Friday the 13th.</item>
    <item name="Phobia" weight="1">Parthenophobia :  Fear of virgins or young girls.</item>
    <item name="Phobia" weight="1">Pathophobia :  Fear of disease.</item>
    <item name="Phobia" weight="1">Patroiophobia :  Fear of heredity.</item>
    <item name="Phobia" weight="1">Parturiphobia :  Fear of childbirth.</item>
    <item name="Phobia" weight="1">Peccatophobia :  Fear of sinning or imaginary crimes.</item>
    <item name="Phobia" weight="1">Pediculophobia :  Fear of lice.</item>
    <item name="Phobia" weight="1">Pediophobia :  Fear of dolls.</item>
    <item name="Phobia" weight="1">Pedophobia :  Fear of children.</item>
    <item name="Phobia" weight="1">Peladophobia :  Fear of bald people.</item>
    <item name="Phobia" weight="1">Pellagrophobia :  Fear of pellagra.</item>
    <item name="Phobia" weight="1">Peniaphobia :  Fear of poverty.</item>
    <item name="Phobia" weight="1">Pentheraphobia :  Fear of mother : in : law. </item>
    <item name="Phobia" weight="1">Phagophobia :  Fear of swallowing or of eating or of being eaten.</item>
    <item name="Phobia" weight="1">Phalacrophobia :  Fear of becoming bald.</item>
    <item name="Phobia" weight="1">Phallophobia :  Fear of a penis, esp erect.</item>
    <item name="Phobia" weight="1">Pharmacophobia :  Fear of taking medicine.</item>
    <item name="Phobia" weight="1">Phasmophobia :  Fear of ghosts.</item>
    <item name="Phobia" weight="1">Phengophobia :  Fear of daylight or sunshine.</item>
    <item name="Phobia" weight="1">Philemaphobia :  Fear of kissing.</item>
    <item name="Phobia" weight="1">Philophobia :  Fear of falling in love or being in love.</item>
    <item name="Phobia" weight="1">Philosophobia :  Fear of philosophy.</item>
    <item name="Phobia" weight="1">Phobophobia :  Fear of phobias.</item>
    <item name="Phobia" weight="1">Photoaugliaphobia :  Fear of glaring lights.</item>
    <item name="Phobia" weight="1">Photophobia :  Fear of light.</item>
    <item name="Phobia" weight="1">Phonophobia :  Fear of noises or voices or one's own voice; of telephones.</item>
    <item name="Phobia" weight="1">Phronemophobia :  Fear of thinking.</item>
    <item name="Phobia" weight="1">Phthiriophobia :  Fear of lice.</item>
    <item name="Phobia" weight="1">Phthisiophobia :  Fear of tuberculosis.</item>
    <item name="Phobia" weight="1">Placophobia :  Fear of tombstones.</item>
    <item name="Phobia" weight="1">Plutophobia :  Fear of wealth.</item>
    <item name="Phobia" weight="1">Pluviophobia :  Fear of rain or of being rained on.</item>
    <item name="Phobia" weight="1">Pneumatiphobia :  Fear of spirits.</item>
    <item name="Phobia" weight="1">Pnigophobia :  Fear of choking of being smothered.</item>
    <item name="Phobia" weight="1">Pocrescophobia :  Fear of gaining weight.</item>
    <item name="Phobia" weight="1">Pogonophobia :  Fear of beards.</item>
    <item name="Phobia" weight="1">Poliosophobia :  Fear of contracting poliomyelitis.</item>
    <item name="Phobia" weight="1">Politicophobia :  Fear or abnormal dislike of politicians.</item>
    <item name="Phobia" weight="1">Polyphobia :  Fear of many things.</item>
    <item name="Phobia" weight="1">Poinephobia :  Fear of punishment.</item>
    <item name="Phobia" weight="1">Ponophobia :  Fear of overworking or of pain.</item>
    <item name="Phobia" weight="1">Porphyrophobia :  Fear of the color purple.</item>
    <item name="Phobia" weight="1">Potamophobia :  Fear of rivers or running water.</item>
    <item name="Phobia" weight="1">Potophobia :  Fear of alcohol.</item>
    <item name="Phobia" weight="1">Pharmacophobia :  Fear of drugs.</item>
    <item name="Phobia" weight="1">Proctophobia :  Fear of rectums.</item>
    <item name="Phobia" weight="1">Prosophobia :  Fear of progress.</item>
    <item name="Phobia" weight="1">Psellismophobia :  Fear of stuttering.</item>
    <item name="Phobia" weight="1">Psychophobia :  Fear of mind.</item>
    <item name="Phobia" weight="1">Psychrophobia :  Fear of cold.</item>
    <item name="Phobia" weight="1">Pteromerhanophobia :  Fear of flying.</item>
    <item name="Phobia" weight="1">Pteronophobia :  Fear of being tickled by feathers.</item>
    <item name="Phobia" weight="1">Pupaphobia  :  Fear of puppets.</item>
    <item name="Phobia" weight="1">Pyrexiophobia :  Fear of Fever.</item>
    <item name="Phobia" weight="1">Pyrophobia :  Fear of fire.</item>
    <item name="Phobia" weight="1">Radiophobia :  Fear of radiation, x : rays.</item>
    <item name="Phobia" weight="1">Ranidaphobia :  Fear of frogs.</item>
    <item name="Phobia" weight="1">Rectophobia :  Fear of rectum or rectal diseases.</item>
    <item name="Phobia" weight="1">Rhabdophobia :  Fear of being severely punished or beaten by a rod, or of being severely criticized. Also fear of magic.(wand)</item>
    <item name="Phobia" weight="1">Rhypophobia :  Fear of defecation.</item>
    <item name="Phobia" weight="1">Rhytiphobia :  Fear of getting wrinkles.</item>
    <item name="Phobia" weight="1">Rupophobia :  Fear of dirt.</item>
    <item name="Phobia" weight="1">Russophobia :  Fear of Russians.</item>
    <item name="Phobia" weight="1">Samhainophobia: Fear of Halloween.</item>
    <item name="Phobia" weight="1">Sarmassophobia :  Fear of love play. </item>
    <item name="Phobia" weight="1">Satanophobia :  Fear of Satan.</item>
    <item name="Phobia" weight="1">Scabiophobia :  Fear of scabies.</item>
    <item name="Phobia" weight="1">Scatophobia :  Fear of fecal matter.</item>
    <item name="Phobia" weight="1">Scelerophibia :  Fear of bad men, burglars.</item>
    <item name="Phobia" weight="1">Sciophobia :  Fear of shadows.</item>
    <item name="Phobia" weight="1">Scoleciphobia :  Fear of worms.</item>
    <item name="Phobia" weight="1">Scolionophobia :  Fear of school.</item>
    <item name="Phobia" weight="1">Scopophobia :  Fear of being seen or stared at.</item>
    <item name="Phobia" weight="1">Scotomaphobia :  Fear of blindness in visual field.</item>
    <item name="Phobia" weight="1">Scotophobia :  Fear of darkness. </item>
    <item name="Phobia" weight="1">Scriptophobia :  Fear of writing in public.</item>
    <item name="Phobia" weight="1">Selachophobia :  Fear of sharks.</item>
    <item name="Phobia" weight="1">Selaphobia :  Fear of light flashes.</item>
    <item name="Phobia" weight="1">Selenophobia :  Fear of the moon.</item>
    <item name="Phobia" weight="1">Seplophobia :  Fear of decaying matter.</item>
    <item name="Phobia" weight="1">Sesquipedalophobia :  Fear of long words.</item>
    <item name="Phobia" weight="1">Sexophobia :  Fear of the opposite sex. </item>
    <item name="Phobia" weight="1">Siderodromophobia :  Fear of trains, railroads or train travel.</item>
    <item name="Phobia" weight="1">Siderophobia :  Fear of stars.</item>
    <item name="Phobia" weight="1">Sinistrophobia :  Fear of things to the left or left : handed.</item>
    <item name="Phobia" weight="1">Sinophobia :  Fear of Chinese, Chinese culture.</item>
    <item name="Phobia" weight="1">Sitophobia :  Fear of food or eating. </item>
    <item name="Phobia" weight="1">Snakephobia :  Fear of snakes. </item>
    <item name="Phobia" weight="1">Soceraphobia :  Fear of parents : in : law.</item>
    <item name="Phobia" weight="1">Social Phobia :  Fear of being evaluated negatively in social situations.</item>
    <item name="Phobia" weight="1">Sociophobia :  Fear of society or people in general.</item>
    <item name="Phobia" weight="1">Somniphobia :  Fear of sleep.</item>
    <item name="Phobia" weight="1">Sophophobia :  Fear of learning.</item>
    <item name="Phobia" weight="1">Soteriophobia  :  Fear of dependence on others.</item>
    <item name="Phobia" weight="1">Spacephobia :  Fear of outer space.</item>
    <item name="Phobia" weight="1">Spectrophobia :  Fear of specters or ghosts.</item>
    <item name="Phobia" weight="1">Spermatophobia :  Fear of germs.</item>
    <item name="Phobia" weight="1">Spheksophobia :  Fear of wasps.</item>
    <item name="Phobia" weight="1">Stasibasiphobia :  Fear of standing or walking.</item>
    <item name="Phobia" weight="1">Staurophobia :  Fear of crosses or the crucifix.</item>
    <item name="Phobia" weight="1">Stenophobia :  Fear of narrow things or places.</item>
    <item name="Phobia" weight="1">Stygiophobia :  Fear of hell.</item>
    <item name="Phobia" weight="1">Suriphobia :  Fear of mice.</item>
    <item name="Phobia" weight="1">Symbolophobia :  Fear of symbolism.</item>
    <item name="Phobia" weight="1">Symmetrophobia :  Fear of symmetry.</item>
    <item name="Phobia" weight="1">Syngenesophobia :  Fear of relatives.</item>
    <item name="Phobia" weight="1">Syphilophobia :  Fear of syphilis.</item>
    <item name="Phobia" weight="1">Tachophobia :  Fear of speed.</item>
    <item name="Phobia" weight="1">Taeniophobia :  Fear of tapeworms.</item>
    <item name="Phobia" weight="1">Taphephobia :  Fear of being buried alive or of cemeteries.</item>
    <item name="Phobia" weight="1">Tapinophobia :  Fear of being contagious.</item>
    <item name="Phobia" weight="1">Taurophobia :  Fear of bulls.</item>
    <item name="Phobia" weight="1">Technophobia :  Fear of technology.</item>
    <item name="Phobia" weight="1">Teleophobia :  Fear of definite plans or religious ceremony.</item>
    <item name="Phobia" weight="1">Telephonophobia :  Fear of telephones.</item>
    <item name="Phobia" weight="1">Teratophobia :  Fear of bearing a deformed child or fear of monsters or deformed people.</item>
    <item name="Phobia" weight="1">Testophobia :  Fear of taking tests.</item>
    <item name="Phobia" weight="1">Tetanophobia :  Fear of lockjaw, tetanus.</item>
    <item name="Phobia" weight="1">Teutophobia :  Fear of German or German things.</item>
    <item name="Phobia" weight="1">Textophobia :  Fear of certain fabrics.</item>
    <item name="Phobia" weight="1">Thaasophobia :  Fear of sitting.</item>
    <item name="Phobia" weight="1">Thalassophobia :  Fear of the sea.</item>
    <item name="Phobia" weight="1">Thanatophobia :  Fear of death or dying.</item>
    <item name="Phobia" weight="1">Theatrophobia :  Fear of theaters.</item>
    <item name="Phobia" weight="1">Theologicophobia :  Fear of theology.</item>
    <item name="Phobia" weight="1">Theophobia :  Fear of gods or religion.</item>
    <item name="Phobia" weight="1">Thermophobia :  Fear of heat.</item>
    <item name="Phobia" weight="1">Tocophobia :  Fear of pregnancy or childbirth.</item>
    <item name="Phobia" weight="1">Tomophobia :  Fear of surgical operations.</item>
    <item name="Phobia" weight="1">Tonitrophobia :  Fear of thunder.</item>
    <item name="Phobia" weight="1">Topophobia :  Fear of certain places or situations, such as stage fright.</item>
    <item name="Phobia" weight="1">Toxiphobia :  Fear of poison or of being accidentally poisoned.</item>
    <item name="Phobia" weight="1">Traumatophobia :  Fear of injury.</item>
    <item name="Phobia" weight="1">Tremophobia :  Fear of trembling.</item>
    <item name="Phobia" weight="1">Trichinophobia :  Fear of trichinosis.</item>
    <item name="Phobia" weight="1">Trichopathophobia  :  Fear of hair.</item>
    <item name="Phobia" weight="1">Triskaidekaphobia :  Fear of the number 13.</item>
    <item name="Phobia" weight="1">Tropophobia :  Fear of moving or making changes.</item>
    <item name="Phobia" weight="1">Trypanophobia :  Fear of injections.</item>
    <item name="Phobia" weight="1">Tuberculophobia :  Fear of tuberculosis.</item>
    <item name="Phobia" weight="1">Tyrannophobia :  Fear of tyrants.</item>
    <item name="Phobia" weight="1">Uranophobia :  Fear of heaven.</item>
    <item name="Phobia" weight="1">Urophobia :  Fear of urine or urinating.</item>
    <item name="Phobia" weight="1">Vaccinophobia :  Fear of vaccination.</item>
    <item name="Phobia" weight="1">Venustraphobia :  Fear of beautiful women.</item>
    <item name="Phobia" weight="1">Verbophobia :  Fear of words.</item>
    <item name="Phobia" weight="1">Verminophobia :  Fear of germs.</item>
    <item name="Phobia" weight="1">Vestiphobia :  Fear of clothing.</item>
    <item name="Phobia" weight="1">Virginitiphobia :  Fear of rape.</item>
    <item name="Phobia" weight="1">Vitricophobia :  Fear of step : father.</item>
    <item name="Phobia" weight="1">Walloonphobia :  Fear of the Walloons.</item>
    <item name="Phobia" weight="1">Wiccaphobia: Fear of witches and witchcraft.</item>
    <item name="Phobia" weight="1">Xanthophobia :  Fear of the color yellow or the word yellow.</item>
    <item name="Phobia" weight="1">Xenoglossophobia :  Fear of foreign languages.</item>
    <item name="Phobia" weight="1">Xenophobia :  Fear of strangers or foreigners.</item>
    <item name="Phobia" weight="1">Xerophobia :  Fear of dryness.</item>
    <item name="Phobia" weight="1">Xylophobia :  Fear of wooden objects or forests.</item>
    <item name="Phobia" weight="1">Xyrophobia : Fear of razors. </item>
    <item name="Phobia" weight="1">Zelophobia :  Fear of jealousy.</item>
    <item name="Phobia" weight="1">Zeusophobia :  Fear of God or gods.</item>
    <item name="Phobia" weight="1">Zemmiphobia :  Fear of the great mole rat.</item>
    <item name="Phobia" weight="1">Zoophobia :  Fear of animals.</item>
  </items>
  <imports />
</generator>