<?xml version="1.0" encoding="utf-16"?>
<generator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:type="Assignment" version="2">
  <name>Technology Jargon</name>
  <author>Lance Boudreaux</author>
  <description>Generates sci-fi techno babble names</description>
  <tags>
    <tag>Name</tag>
    <tag>Sci-Fi</tag>
  </tags>
  <supportsMaxLength>false</supportsMaxLength>
  <isLibrary>false</isLibrary>
  <items>
    <item name="Start" weight="1">[GeneralPrefix][General][GeneralSuffix]</item>
    <item name="Start" weight="1">[GeneralPrefix][General]</item>
    <item name="Start" weight="1">[General][GeneralSuffix]</item>
    <item name="Start" weight="1">[Units][General]</item>
    <item name="Start" weight="1">[GeneralPrefix][Units][General]</item>
    <item name="Start" weight="1">[Units][Particle][General]</item>
    <item name="Start" weight="1">[Particle][Beams]</item>
    <item name="Start" weight="1">[Cosmic][General]</item>
    <item name="Start" weight="1">[Cosmic][Beams]</item>
    <item name="Start" weight="1">[GeneralPrefix][Beams]</item>
    <item name="Start" weight="1">[Beams][GeneralSuffix]</item>
    <item name="Start" weight="1">[GeneralPrefix][GeneralSuffix]</item>
    <item name="Start" weight="1">i[General]</item>
    <item name="GeneralPrefix" weight="1">mechano</item>
    <item name="GeneralPrefix" weight="1">mecha</item>
    <item name="GeneralPrefix" weight="1">electro</item>
    <item name="GeneralPrefix" weight="1">morpho</item>
    <item name="GeneralPrefix" weight="1">dyna</item>
    <item name="GeneralPrefix" weight="1">gravi</item>
    <item name="GeneralPrefix" weight="1">robo</item>
    <item name="GeneralPrefix" weight="1">atomic</item>
    <item name="GeneralPrefix" weight="1">cyber</item>
    <item name="GeneralPrefix" weight="1">compu</item>
    <item name="GeneralPrefix" weight="1">neuro</item>
    <item name="GeneralPrefix" weight="1">cyclo</item>
    <item name="GeneralPrefix" weight="1">synchro</item>
    <item name="GeneralPrefix" weight="1">turbo</item>
    <item name="GeneralPrefix" weight="1">meta</item>
    <item name="GeneralPrefix" weight="1">e</item>
    <item name="GeneralPrefix" weight="1">gyro</item>
    <item name="GeneralPrefix" weight="1">aether</item>
    <item name="GeneralPrefix" weight="1">mag</item>
    <item name="GeneralPrefix" weight="1">magno</item>
    <item name="GeneralPrefix" weight="1">magneto</item>
    <item name="GeneralPrefix" weight="1">pneumatic</item>
    <item name="GeneralSuffix" weight="1">tron</item>
    <item name="GeneralSuffix" weight="1">tor</item>
    <item name="GeneralSuffix" weight="1">ite</item>
    <item name="GeneralSuffix" weight="1">ium</item>
    <item name="GeneralSuffix" weight="1">oid</item>
    <item name="GeneralSuffix" weight="1">izer</item>
    <item name="GeneralSuffix" weight="1">inator</item>
    <item name="GeneralSuffix" weight="1">graph</item>
    <item name="General" weight="1">matrix</item>
    <item name="General" weight="1">fusion</item>
    <item name="General" weight="1">core</item>
    <item name="General" weight="1">reactor</item>
    <item name="General" weight="1">machine</item>
    <item name="General" weight="1">engine</item>
    <item name="General" weight="1">drive</item>
    <item name="General" weight="1">thruster</item>
    <item name="General" weight="1">gun</item>
    <item name="General" weight="1">apparatus</item>
    <item name="General" weight="1">rifle</item>
    <item name="General" weight="1">blaster</item>
    <item name="General" weight="1">saber</item>
    <item name="General" weight="1">sword</item>
    <item name="General" weight="1">planet</item>
    <item name="General" weight="1">moon</item>
    <item name="General" weight="1">asteroid</item>
    <item name="General" weight="1">comet</item>
    <item name="General" weight="1">console</item>
    <item name="General" weight="1">communicator</item>
    <item name="General" weight="1">transponder</item>
    <item name="General" weight="1">cloner</item>
    <item name="General" weight="1">computer</item>
    <item name="Units" weight="1">macro</item>
    <item name="Units" weight="1">mega</item>
    <item name="Units" weight="1">giga</item>
    <item name="Units" weight="1">tera</item>
    <item name="Units" weight="1">peta</item>
    <item name="Units" weight="1">micro</item>
    <item name="Units" weight="1">nano</item>
    <item name="Units" weight="1">pico</item>
    <item name="Units" weight="1">femto</item>
    <item name="Particle" weight="1">atomic</item>
    <item name="Particle" weight="1">nuclear</item>
    <item name="Particle" weight="1">nucleo</item>
    <item name="Particle" weight="1">quantum</item>
    <item name="Particle" weight="1">photon</item>
    <item name="Particle" weight="1">proton</item>
    <item name="Particle" weight="1">neutron</item>
    <item name="Particle" weight="1">electron</item>
    <item name="Particle" weight="1">molecular</item>
    <item name="Particle" weight="1">positron</item>
    <item name="Particle" weight="1">tachyon</item>
    <item name="Particle" weight="1">lambda</item>
    <item name="Particle" weight="1">muon</item>
    <item name="Particle" weight="1">ion</item>
    <item name="Particle" weight="1">particle</item>
    <item name="Beams" weight="1">laser</item>
    <item name="Beams" weight="1">graser</item>
    <item name="Beams" weight="1">maser</item>
    <item name="Beams" weight="1">uvaser</item>
    <item name="Beams" weight="1">xaser</item>
    <item name="Beams" weight="1">taser</item>
    <item name="Beams" weight="1">phaser</item>
    <item name="Beams" weight="1">blazer</item>
    <item name="Beams" weight="1">stazer</item>
    <item name="Beams" weight="1">gauss</item>
    <item name="Cosmic" weight="1">space</item>
    <item name="Cosmic" weight="1">star</item>
    <item name="Cosmic" weight="1">galactic</item>
    <item name="Cosmic" weight="1">intergalactic</item>
    <item name="Cosmic" weight="1">vortex</item>
    <item name="Cosmic" weight="1">astro</item>
    <item name="Cosmic" weight="1">cosmo</item>
    <item name="Cosmic" weight="1">hyper</item>
    <item name="Cosmic" weight="1">warp</item>
    <item name="Cosmic" weight="1">phase</item>
    <item name="Cosmic" weight="1">orbital</item>
    <item name="Cosmic" weight="1">planetary</item>
    <item name="Cosmic" weight="1">interplanetary</item>
    <item name="Cosmic" weight="1">stellar</item>
    <item name="Cosmic" weight="1">interstellar</item>
    <item name="Cosmic" weight="1">flux</item>
    <item name="Cosmic" weight="1">node</item>
  </items>
  <imports />
</generator>